// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_setup.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const consumeAccountSetupToken = `-- name: ConsumeAccountSetupToken :one
UPDATE account_setup_tokens
SET consumed_at = NOW()
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
RETURNING user_id
`

// Atomic consume: marks the row as used (consumed_at = NOW()) and returns
// the matching user_id only if the token is unconsumed AND unexpired.
// The single UPDATE … RETURNING form leaves no read-modify-write window
// where two concurrent set-password requests could both succeed.
// A second use of the same token returns 0 rows because consumed_at is
// no longer NULL.
func (q *Queries) ConsumeAccountSetupToken(ctx context.Context, tokenHash string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, consumeAccountSetupToken, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const deleteExpiredAccountSetupTokens = `-- name: DeleteExpiredAccountSetupTokens :exec
DELETE FROM account_setup_tokens
WHERE expires_at < NOW()
`

// Periodic sweep of stale rows. Safe to run on a cron — leaves
// still-valid and recently-consumed tokens untouched. consumed_at rows
// are kept until they also expire so replays of a freshly-used token
// still get a clean "invalid or expired" rather than slipping through
// as a not-found.
func (q *Queries) DeleteExpiredAccountSetupTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAccountSetupTokens)
	return err
}

const getAccountSetupTokenStatus = `-- name: GetAccountSetupTokenStatus :one
SELECT consumed_at, expires_at
FROM account_setup_tokens
WHERE user_id = $1
`

type GetAccountSetupTokenStatusRow struct {
	ConsumedAt sql.NullTime
	ExpiresAt  time.Time
}

// Look up by user_id (NOT by token) so the admin "is this trainer
// already activated?" check doesn't need the original token. Returns the
// consumed_at column so callers can distinguish "never invited",
// "invite pending", and "already activated". Used by the trainer create
// handler when an admin re-invites an existing email.
func (q *Queries) GetAccountSetupTokenStatus(ctx context.Context, userID uuid.UUID) (GetAccountSetupTokenStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getAccountSetupTokenStatus, userID)
	var i GetAccountSetupTokenStatusRow
	err := row.Scan(&i.ConsumedAt, &i.ExpiresAt)
	return i, err
}

const peekAccountSetupToken = `-- name: PeekAccountSetupToken :one
SELECT consumed_at, expires_at
FROM account_setup_tokens
WHERE token_hash = $1
`

type PeekAccountSetupTokenRow struct {
	ConsumedAt sql.NullTime
	ExpiresAt  time.Time
}

// Read-only validity check for the set-password FE page. Looks up the row
// by token_hash but does NOT mark it consumed — callers use this to
// pre-render "your link expired" / "this link was already used" UI before
// they ever ask the user to type a password.
//
// Returns consumed_at and expires_at so the handler can return a precise
// reason (valid / expired / used) for the FE — there's no enumeration
// concern here because the token IS the secret: an attacker would already
// need to possess a valid hash to learn anything, at which point they'd
// just use the consume endpoint instead.
func (q *Queries) PeekAccountSetupToken(ctx context.Context, tokenHash string) (PeekAccountSetupTokenRow, error) {
	row := q.db.QueryRowContext(ctx, peekAccountSetupToken, tokenHash)
	var i PeekAccountSetupTokenRow
	err := row.Scan(&i.ConsumedAt, &i.ExpiresAt)
	return i, err
}

const updateUserPasswordByID = `-- name: UpdateUserPasswordByID :one
UPDATE users SET password = $2, updated_at = NOW()
WHERE id = $1 AND auth_provider = 'local' AND is_active = true
RETURNING id, email, name, password, auth_provider, is_active, created_at, updated_at, role, gender, fitness_goals, fitness_level, avatar_url
`

type UpdateUserPasswordByIDParams struct {
	ID       uuid.UUID
	Password sql.NullString
}

// ID-keyed variant of UpdateUserPassword used by the account-setup flow.
// That flow only knows the user_id (resolved from the supplied token);
// the email-keyed UpdateUserPassword would require an extra lookup and
// leak email-vs-not-email through wall-clock time. Same is_active +
// auth_provider guard so a deactivated or social-only account can't be
// silently password-set.
func (q *Queries) UpdateUserPasswordByID(ctx context.Context, arg UpdateUserPasswordByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPasswordByID, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Gender,
		pq.Array(&i.FitnessGoals),
		&i.FitnessLevel,
		&i.AvatarUrl,
	)
	return i, err
}

const upsertAccountSetupToken = `-- name: UpsertAccountSetupToken :exec
INSERT INTO account_setup_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET token_hash  = EXCLUDED.token_hash,
    expires_at  = EXCLUDED.expires_at,
    consumed_at = NULL,
    created_at  = NOW()
`

type UpsertAccountSetupTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

// Issue (or rotate) the setup token for a user. Single-statement
// INSERT … ON CONFLICT (user_id) so a re-invite atomically clears the
// previous token and re-arms consumed_at to NULL. The PRIMARY KEY on
// user_id makes this race-free without an outer transaction.
func (q *Queries) UpsertAccountSetupToken(ctx context.Context, arg UpsertAccountSetupTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccountSetupToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}
