// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_invite.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAdminInvite = `-- name: CreateAdminInvite :one
INSERT INTO admin_invites (email, name, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at
`

type CreateAdminInviteParams struct {
	Email     string
	Name      string
	TokenHash string
	InvitedBy uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateAdminInvite(ctx context.Context, arg CreateAdminInviteParams) (AdminInvite, error) {
	row := q.db.QueryRowContext(ctx, createAdminInvite,
		arg.Email,
		arg.Name,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i AdminInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminInviteByTokenHash = `-- name: GetAdminInviteByTokenHash :one
SELECT id, email, name, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM admin_invites WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetAdminInviteByTokenHash(ctx context.Context, tokenHash string) (AdminInvite, error) {
	row := q.db.QueryRowContext(ctx, getAdminInviteByTokenHash, tokenHash)
	var i AdminInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasPendingInviteForEmail = `-- name: HasPendingInviteForEmail :one
SELECT EXISTS (
    SELECT 1 FROM admin_invites
    WHERE email = $1
      AND accepted_at IS NULL
      AND revoked_at IS NULL
      AND expires_at > NOW()
) AS has_pending
`

func (q *Queries) HasPendingInviteForEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasPendingInviteForEmail, email)
	var has_pending bool
	err := row.Scan(&has_pending)
	return has_pending, err
}

const markAdminInviteAccepted = `-- name: MarkAdminInviteAccepted :exec
UPDATE admin_invites SET accepted_at = NOW() WHERE id = $1
`

func (q *Queries) MarkAdminInviteAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAdminInviteAccepted, id)
	return err
}
