// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_settings.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getAdminSettings = `-- name: GetAdminSettings :one
SELECT
    id,
    default_session_duration_min,
    max_trainers_displayed,
    require_video_before_listing,
    auto_assign_trainer,
    updated_at
FROM admin_settings
WHERE singleton_lock = 'singleton'
LIMIT 1
`

type GetAdminSettingsRow struct {
	ID                        uuid.UUID
	DefaultSessionDurationMin int32
	MaxTrainersDisplayed      int32
	RequireVideoBeforeListing bool
	AutoAssignTrainer         bool
	UpdatedAt                 time.Time
}

// Reads the singleton row. The migration seeds it on first apply, so
// a missing row here is a hard error worth surfacing — never expected
// in normal operation.
func (q *Queries) GetAdminSettings(ctx context.Context) (GetAdminSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminSettings)
	var i GetAdminSettingsRow
	err := row.Scan(
		&i.ID,
		&i.DefaultSessionDurationMin,
		&i.MaxTrainersDisplayed,
		&i.RequireVideoBeforeListing,
		&i.AutoAssignTrainer,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminSettings = `-- name: UpdateAdminSettings :one
UPDATE admin_settings
SET
    default_session_duration_min = COALESCE($1::int,  default_session_duration_min),
    max_trainers_displayed       = COALESCE($2::int,        max_trainers_displayed),
    require_video_before_listing = COALESCE($3::bool, require_video_before_listing),
    auto_assign_trainer          = COALESCE($4::bool,          auto_assign_trainer),
    updated_at                   = NOW()
WHERE singleton_lock = 'singleton'
RETURNING
    id,
    default_session_duration_min,
    max_trainers_displayed,
    require_video_before_listing,
    auto_assign_trainer,
    updated_at
`

type UpdateAdminSettingsParams struct {
	DefaultSessionDurationMin sql.NullInt32
	MaxTrainersDisplayed      sql.NullInt32
	RequireVideoBeforeListing sql.NullBool
	AutoAssignTrainer         sql.NullBool
}

type UpdateAdminSettingsRow struct {
	ID                        uuid.UUID
	DefaultSessionDurationMin int32
	MaxTrainersDisplayed      int32
	RequireVideoBeforeListing bool
	AutoAssignTrainer         bool
	UpdatedAt                 time.Time
}

// Partial-update via COALESCE: pass NULL for any field the caller
// doesn't want to change, the existing value is kept. Lets the FE
// submit only the toggled rows from the settings form rather than
// having to re-send every field.
func (q *Queries) UpdateAdminSettings(ctx context.Context, arg UpdateAdminSettingsParams) (UpdateAdminSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, updateAdminSettings,
		arg.DefaultSessionDurationMin,
		arg.MaxTrainersDisplayed,
		arg.RequireVideoBeforeListing,
		arg.AutoAssignTrainer,
	)
	var i UpdateAdminSettingsRow
	err := row.Scan(
		&i.ID,
		&i.DefaultSessionDurationMin,
		&i.MaxTrainersDisplayed,
		&i.RequireVideoBeforeListing,
		&i.AutoAssignTrainer,
		&i.UpdatedAt,
	)
	return i, err
}
