// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAvailabilitySlotByID = `-- name: DeleteAvailabilitySlotByID :execrows
DELETE FROM trainer_availability
WHERE id = $1 AND trainer_id = $2
`

type DeleteAvailabilitySlotByIDParams struct {
	ID        uuid.UUID
	TrainerID uuid.UUID
}

// Single-row delete used by DELETE /trainers/.../availability/{slot_id}.
// The trainer_id predicate is the data-layer authz check: even if a
// caller guesses another trainer's slot UUID, the row won't match and
// the handler returns 404. Returns rowsAffected so the handler can
// distinguish "not found / not yours" from a real DB error.
func (q *Queries) DeleteAvailabilitySlotByID(ctx context.Context, arg DeleteAvailabilitySlotByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAvailabilitySlotByID, arg.ID, arg.TrainerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTrainerAvailabilitySlots = `-- name: DeleteTrainerAvailabilitySlots :exec
DELETE FROM trainer_availability
WHERE trainer_id = $1
`

func (q *Queries) DeleteTrainerAvailabilitySlots(ctx context.Context, trainerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTrainerAvailabilitySlots, trainerID)
	return err
}

const getTrainerAvailabilitySlots = `-- name: GetTrainerAvailabilitySlots :many
SELECT
  id,
  trainer_id,
  day_of_week,
  start_time,
  end_time,
  timezone,
  created_at,
  updated_at
FROM trainer_availability
WHERE trainer_id = $1
ORDER BY day_of_week ASC, start_time ASC
`

func (q *Queries) GetTrainerAvailabilitySlots(ctx context.Context, trainerID uuid.UUID) ([]TrainerAvailability, error) {
	rows, err := q.db.QueryContext(ctx, getTrainerAvailabilitySlots, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainerAvailability
	for rows.Next() {
		var i TrainerAvailability
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAvailabilitySlot = `-- name: InsertAvailabilitySlot :one
INSERT INTO trainer_availability (
  trainer_id,
  day_of_week,
  start_time,
  end_time,
  timezone
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  trainer_id,
  day_of_week,
  start_time,
  end_time,
  timezone,
  created_at,
  updated_at
`

type InsertAvailabilitySlotParams struct {
	TrainerID uuid.UUID
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
}

func (q *Queries) InsertAvailabilitySlot(ctx context.Context, arg InsertAvailabilitySlotParams) (TrainerAvailability, error) {
	row := q.db.QueryRowContext(ctx, insertAvailabilitySlot,
		arg.TrainerID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
	)
	var i TrainerAvailability
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
