// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking_session.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const collectTrainersNote = `-- name: CollectTrainersNote :one
UPDATE booking_session
SET
    trainer_notes=$1
WHERE id=$2
AND status='completed'
RETURNING
    id,
    booking_id,
    actual_start,
    actual_end,
    trainer_joined,
    client_joined,
    status,
    trainer_notes,
    created_at
`

type CollectTrainersNoteParams struct {
	TrainerNotes sql.NullString
	ID           uuid.UUID
}

func (q *Queries) CollectTrainersNote(ctx context.Context, arg CollectTrainersNoteParams) (BookingSession, error) {
	row := q.db.QueryRowContext(ctx, collectTrainersNote, arg.TrainerNotes, arg.ID)
	var i BookingSession
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ActualStart,
		&i.ActualEnd,
		&i.TrainerJoined,
		&i.ClientJoined,
		&i.Status,
		&i.TrainerNotes,
		&i.CreatedAt,
	)
	return i, err
}

const createBookingSession = `-- name: CreateBookingSession :one
INSERT INTO booking_session (
    booking_id,
    actual_start
) VALUES (
    $1,
    $2
)
RETURNING
id,
booking_id,
actual_start,
actual_end,
trainer_joined,
client_joined,
status,
trainer_notes,
created_at
`

type CreateBookingSessionParams struct {
	BookingID   uuid.UUID
	ActualStart sql.NullTime
}

func (q *Queries) CreateBookingSession(ctx context.Context, arg CreateBookingSessionParams) (BookingSession, error) {
	row := q.db.QueryRowContext(ctx, createBookingSession, arg.BookingID, arg.ActualStart)
	var i BookingSession
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ActualStart,
		&i.ActualEnd,
		&i.TrainerJoined,
		&i.ClientJoined,
		&i.Status,
		&i.TrainerNotes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBookingSessionByID = `-- name: DeleteBookingSessionByID :exec
DELETE FROM booking_session
WHERE id = $1
`

func (q *Queries) DeleteBookingSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBookingSessionByID, id)
	return err
}

const getBookingSessionByBookingID = `-- name: GetBookingSessionByBookingID :one
SELECT
    id,
    booking_id,
    actual_start,
    actual_end,
    trainer_joined,
    client_joined,
    status,
    trainer_notes,
    created_at
FROM booking_session
WHERE booking_id = $1
LIMIT 1
`

func (q *Queries) GetBookingSessionByBookingID(ctx context.Context, bookingID uuid.UUID) (BookingSession, error) {
	row := q.db.QueryRowContext(ctx, getBookingSessionByBookingID, bookingID)
	var i BookingSession
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ActualStart,
		&i.ActualEnd,
		&i.TrainerJoined,
		&i.ClientJoined,
		&i.Status,
		&i.TrainerNotes,
		&i.CreatedAt,
	)
	return i, err
}

const getBookingSessionById = `-- name: GetBookingSessionById :one
SELECT
    bs.id,
    bs.booking_id,
    bs.actual_start,
    bs.actual_end,
    bs.trainer_joined,
    bs.client_joined,
    bs.status,
    bs.trainer_notes,
    bs.created_at,
    b.trainer_id
FROM booking_session bs
JOIN bookings b ON b.id = bs.booking_id
WHERE bs.id = $1
LIMIT 1
`

type GetBookingSessionByIdRow struct {
	ID            uuid.UUID
	BookingID     uuid.UUID
	ActualStart   sql.NullTime
	ActualEnd     sql.NullTime
	TrainerJoined sql.NullBool
	ClientJoined  sql.NullBool
	Status        string
	TrainerNotes  sql.NullString
	CreatedAt     time.Time
	TrainerID     uuid.UUID
}

// Joins the parent booking so we can return the trainer_id alongside the
// session — the client uses it to look up trainer details without an
// extra round trip.
func (q *Queries) GetBookingSessionById(ctx context.Context, id uuid.UUID) (GetBookingSessionByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getBookingSessionById, id)
	var i GetBookingSessionByIdRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ActualStart,
		&i.ActualEnd,
		&i.TrainerJoined,
		&i.ClientJoined,
		&i.Status,
		&i.TrainerNotes,
		&i.CreatedAt,
		&i.TrainerID,
	)
	return i, err
}

const markSessionAsCompleted = `-- name: MarkSessionAsCompleted :one
UPDATE booking_session
SET
    actual_end=$1,
    status=$2
WHERE id=$3
AND status IN ('started', 'in-session')
RETURNING
    id,
    booking_id,
    actual_start,
    actual_end,
    trainer_joined,
    client_joined,
    status,
    trainer_notes,
    created_at
`

type MarkSessionAsCompletedParams struct {
	ActualEnd sql.NullTime
	Status    string
	ID        uuid.UUID
}

func (q *Queries) MarkSessionAsCompleted(ctx context.Context, arg MarkSessionAsCompletedParams) (BookingSession, error) {
	row := q.db.QueryRowContext(ctx, markSessionAsCompleted, arg.ActualEnd, arg.Status, arg.ID)
	var i BookingSession
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ActualStart,
		&i.ActualEnd,
		&i.TrainerJoined,
		&i.ClientJoined,
		&i.Status,
		&i.TrainerNotes,
		&i.CreatedAt,
	)
	return i, err
}

const markSessionAsJoined = `-- name: MarkSessionAsJoined :one
UPDATE booking_session
SET
    client_joined=$1,
    status=$2
WHERE id=$3
AND status='started'
RETURNING
    id,
    booking_id,
    actual_start,
    actual_end,
    trainer_joined,
    client_joined,
    status,
    trainer_notes,
    created_at
`

type MarkSessionAsJoinedParams struct {
	ClientJoined sql.NullBool
	Status       string
	ID           uuid.UUID
}

func (q *Queries) MarkSessionAsJoined(ctx context.Context, arg MarkSessionAsJoinedParams) (BookingSession, error) {
	row := q.db.QueryRowContext(ctx, markSessionAsJoined, arg.ClientJoined, arg.Status, arg.ID)
	var i BookingSession
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ActualStart,
		&i.ActualEnd,
		&i.TrainerJoined,
		&i.ClientJoined,
		&i.Status,
		&i.TrainerNotes,
		&i.CreatedAt,
	)
	return i, err
}

const markSessionAsStarted = `-- name: MarkSessionAsStarted :one
UPDATE booking_session
SET
    actual_start=$1,
    trainer_joined=$2,
    status=$3
WHERE id=$4
AND status='booked'
RETURNING
    id,
    booking_id,
    actual_start,
    actual_end,
    trainer_joined,
    client_joined,
    status,
    trainer_notes,
    created_at
`

type MarkSessionAsStartedParams struct {
	ActualStart   sql.NullTime
	TrainerJoined sql.NullBool
	Status        string
	ID            uuid.UUID
}

func (q *Queries) MarkSessionAsStarted(ctx context.Context, arg MarkSessionAsStartedParams) (BookingSession, error) {
	row := q.db.QueryRowContext(ctx, markSessionAsStarted,
		arg.ActualStart,
		arg.TrainerJoined,
		arg.Status,
		arg.ID,
	)
	var i BookingSession
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ActualStart,
		&i.ActualEnd,
		&i.TrainerJoined,
		&i.ClientJoined,
		&i.Status,
		&i.TrainerNotes,
		&i.CreatedAt,
	)
	return i, err
}
