// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking_slots.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getBookingSlots = `-- name: GetBookingSlots :many
SELECT
    id,
    trainer_id,
    day_of_week,
    start_time,
    end_time,
    timezone,
    is_active,
    created_at,
    updated_at
FROM booking_slots
`

type GetBookingSlotsRow struct {
	ID        uuid.UUID
	TrainerID uuid.NullUUID
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetBookingSlots(ctx context.Context) ([]GetBookingSlotsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookingSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookingSlotsRow
	for rows.Next() {
		var i GetBookingSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainersBookingSlots = `-- name: GetTrainersBookingSlots :many
SELECT
    id,
    day_of_week,
    start_time,
    end_time,
    timezone,
    is_active,
    created_at,
    updated_at
FROM booking_slots
WHERE trainer_id = $1
`

type GetTrainersBookingSlotsRow struct {
	ID        uuid.UUID
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetTrainersBookingSlots(ctx context.Context, trainerID uuid.NullUUID) ([]GetTrainersBookingSlotsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTrainersBookingSlots, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrainersBookingSlotsRow
	for rows.Next() {
		var i GetTrainersBookingSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
