// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking_slots.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBookingSlot = `-- name: CreateBookingSlot :one
INSERT INTO booking_slots (
  trainer_id,
  starts_at,
  ends_at,
  timezone,
  status,
  locked_by,
  locked_at
) VALUES (
  $1,
  $2,
  $3,
  COALESCE($4, 'UTC'),
  COALESCE($5, 'available'),
  $6,
  $7
)
RETURNING
  id,
  trainer_id,
  starts_at,
  ends_at,
  timezone,
  status,
  locked_by,
  locked_at,
  booking_id,
  created_at,
  updated_at
`

type CreateBookingSlotParams struct {
	TrainerID uuid.UUID
	StartsAt  time.Time
	EndsAt    time.Time
	Timezone  interface{}
	Status    interface{}
	LockedBy  uuid.NullUUID
	LockedAt  sql.NullTime
}

func (q *Queries) CreateBookingSlot(ctx context.Context, arg CreateBookingSlotParams) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, createBookingSlot,
		arg.TrainerID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Timezone,
		arg.Status,
		arg.LockedBy,
		arg.LockedAt,
	)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Status,
		&i.LockedBy,
		&i.LockedAt,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingSlotByID = `-- name: GetBookingSlotByID :one
SELECT
  id,
  trainer_id,
  starts_at,
  ends_at,
  timezone,
  status,
  locked_by,
  locked_at,
  booking_id,
  created_at,
  updated_at
FROM booking_slots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBookingSlotByID(ctx context.Context, id uuid.UUID) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, getBookingSlotByID, id)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Status,
		&i.LockedBy,
		&i.LockedAt,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingSlotByIDForUpdate = `-- name: GetBookingSlotByIDForUpdate :one
SELECT
  id,
  trainer_id,
  starts_at,
  ends_at,
  timezone,
  status,
  locked_by,
  locked_at,
  booking_id,
  created_at,
  updated_at
FROM booking_slots
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetBookingSlotByIDForUpdate(ctx context.Context, id uuid.UUID) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, getBookingSlotByIDForUpdate, id)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Status,
		&i.LockedBy,
		&i.LockedAt,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockBookingSlotIfAvailable = `-- name: LockBookingSlotIfAvailable :one
UPDATE booking_slots
SET
  status = 'locked',
  locked_by = $1,
  locked_at = NOW(),
  updated_at = NOW()
WHERE id = $2
  AND trainer_id = $3
  AND status = 'available'
RETURNING
  id,
  trainer_id,
  starts_at,
  ends_at,
  timezone,
  status,
  locked_by,
  locked_at,
  booking_id,
  created_at,
  updated_at
`

type LockBookingSlotIfAvailableParams struct {
	LockedBy  uuid.NullUUID
	SlotID    uuid.UUID
	TrainerID uuid.UUID
}

func (q *Queries) LockBookingSlotIfAvailable(ctx context.Context, arg LockBookingSlotIfAvailableParams) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, lockBookingSlotIfAvailable, arg.LockedBy, arg.SlotID, arg.TrainerID)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Status,
		&i.LockedBy,
		&i.LockedAt,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBookingSlotBooked = `-- name: MarkBookingSlotBooked :one
UPDATE booking_slots
SET
  status = 'booked',
  booking_id = $1,
  locked_by = NULL,
  locked_at = NULL,
  updated_at = NOW()
WHERE id = $2
RETURNING
  id,
  trainer_id,
  starts_at,
  ends_at,
  timezone,
  status,
  locked_by,
  locked_at,
  booking_id,
  created_at,
  updated_at
`

type MarkBookingSlotBookedParams struct {
	BookingID uuid.NullUUID
	SlotID    uuid.UUID
}

func (q *Queries) MarkBookingSlotBooked(ctx context.Context, arg MarkBookingSlotBookedParams) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, markBookingSlotBooked, arg.BookingID, arg.SlotID)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Status,
		&i.LockedBy,
		&i.LockedAt,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
