// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET
  booking_status = 'cancelled',
  cancellation_reason = $1,
  cancelled_at = NOW()
WHERE id = $2
RETURNING
  id,
  trainer_id,
  client_id,
  subscription_id,
  calendly_event_id,
  scheduled_start,
  scheduled_end,
  timezone,
  booking_status,
  session_platform,
  cancellation_reason,
  created_at,
  cancelled_at
`

type CancelBookingParams struct {
	CancellationReason sql.NullString
	ID                 uuid.UUID
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, cancelBooking, arg.CancellationReason, arg.ID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.ClientID,
		&i.SubscriptionID,
		&i.CalendlyEventID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.Timezone,
		&i.BookingStatus,
		&i.SessionPlatform,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  trainer_id,
  client_id,
  subscription_id,
  calendly_event_id,
  scheduled_start,
  scheduled_end,
  timezone,
  booking_status,
  session_platform,
  cancellation_reason,
  created_at,
  cancelled_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12
)
RETURNING
  id,
  trainer_id,
  client_id,
  subscription_id,
  calendly_event_id,
  scheduled_start,
  scheduled_end,
  timezone,
  booking_status,
  session_platform,
  cancellation_reason,
  created_at,
  cancelled_at
`

type CreateBookingParams struct {
	TrainerID          uuid.UUID
	ClientID           uuid.UUID
	SubscriptionID     uuid.NullUUID
	CalendlyEventID    sql.NullString
	ScheduledStart     sql.NullTime
	ScheduledEnd       sql.NullTime
	Timezone           sql.NullString
	BookingStatus      sql.NullString
	SessionPlatform    sql.NullString
	CancellationReason sql.NullString
	CreatedAt          sql.NullTime
	CancelledAt        sql.NullTime
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.TrainerID,
		arg.ClientID,
		arg.SubscriptionID,
		arg.CalendlyEventID,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.Timezone,
		arg.BookingStatus,
		arg.SessionPlatform,
		arg.CancellationReason,
		arg.CreatedAt,
		arg.CancelledAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.ClientID,
		&i.SubscriptionID,
		&i.CalendlyEventID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.Timezone,
		&i.BookingStatus,
		&i.SessionPlatform,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT
  id,
  trainer_id,
  client_id,
  subscription_id,
  calendly_event_id,
  scheduled_start,
  scheduled_end,
  timezone,
  booking_status,
  session_platform,
  cancellation_reason,
  created_at,
  cancelled_at
FROM bookings
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBookingByID(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByID, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.ClientID,
		&i.SubscriptionID,
		&i.CalendlyEventID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.Timezone,
		&i.BookingStatus,
		&i.SessionPlatform,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getBookingByIDForUpdate = `-- name: GetBookingByIDForUpdate :one
SELECT
  id,
  trainer_id,
  client_id,
  subscription_id,
  calendly_event_id,
  scheduled_start,
  scheduled_end,
  timezone,
  booking_status,
  session_platform,
  cancellation_reason,
  created_at,
  cancelled_at
FROM bookings
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetBookingByIDForUpdate(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBookingByIDForUpdate, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.ClientID,
		&i.SubscriptionID,
		&i.CalendlyEventID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.Timezone,
		&i.BookingStatus,
		&i.SessionPlatform,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const releaseBookingSlot = `-- name: ReleaseBookingSlot :exec
UPDATE booking_slots
SET
  is_active = true,
  updated_at = NOW()
WHERE
  trainer_id = $1
  AND day_of_week = EXTRACT(DOW FROM $3::TIMESTAMPTZ AT TIME ZONE $2::TEXT)::SMALLINT
  AND start_time = ($3::TIMESTAMPTZ AT TIME ZONE $2::TEXT)::TIME
  AND end_time = ($4::TIMESTAMPTZ AT TIME ZONE $2::TEXT)::TIME
  AND timezone = $2
`

type ReleaseBookingSlotParams struct {
	TrainerID      uuid.NullUUID
	Timezone       string
	ScheduledStart time.Time
	ScheduledEnd   time.Time
}

// Release a booking slot by marking it as available again
// This updates the booking_slots table to set is_active = true for the slot used by this booking
func (q *Queries) ReleaseBookingSlot(ctx context.Context, arg ReleaseBookingSlotParams) error {
	_, err := q.db.ExecContext(ctx, releaseBookingSlot,
		arg.TrainerID,
		arg.Timezone,
		arg.ScheduledStart,
		arg.ScheduledEnd,
	)
	return err
}
