// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at
`

type CreateCategoryParams struct {
	Name string
	Slug string
}

// name is the display label; slug is the URL-safe identifier. Both
// enforced UNIQUE at the schema level — the handler maps 23505
// (unique violation) to 409 Conflict so the admin sees a clean
// "already exists" message instead of a 500.
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1
`

// Returns the affected row count so the handler can 404 cleanly when
// the id doesn't exist rather than returning 204 in both cases (which
// would make "already gone" indistinguishable from "really gone now").
func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, created_at, updated_at
FROM categories
ORDER BY name ASC
`

// Used by both the admin settings page (which shows them as chips
// with × delete) and the client-facing /categories endpoint. Stable
// order by name so the FE doesn't have to sort.
func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
