// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO contact_messages (email, subject, message, name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, subject, message, name, created_at
`

type CreateMessageParams struct {
	Email   string
	Subject string
	Message string
	Name    string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ContactMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.Email,
		arg.Subject,
		arg.Message,
		arg.Name,
	)
	var i ContactMessage
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Subject,
		&i.Message,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByEmail = `-- name: GetMessageByEmail :many
SELECT id, email, subject, message, name, created_at
FROM contact_messages
WHERE email = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMessageByEmail(ctx context.Context, email string) ([]ContactMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessageByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactMessage
	for rows.Next() {
		var i ContactMessage
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Subject,
			&i.Message,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, email, subject, message, name, created_at
FROM contact_messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (ContactMessage, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i ContactMessage
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Subject,
		&i.Message,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
