// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkSlotConflict = `-- name: CheckSlotConflict :one
SELECT COUNT(*) FROM discovery_bookings
WHERE selected_datetime > $1::timestamptz - INTERVAL '30 minutes'
  AND selected_datetime < $1::timestamptz + INTERVAL '30 minutes'
  AND status NOT IN ('cancelled', 'completed')
`

func (q *Queries) CheckSlotConflict(ctx context.Context, selectedDatetime time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkSlotConflict, selectedDatetime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBookingSlot = `-- name: CreateBookingSlot :one
INSERT INTO booking_slots (
    day_of_week,
    start_time,
    end_time,
    timezone,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    true
)
RETURNING id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at, trainer_id
`

type CreateBookingSlotParams struct {
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
}

func (q *Queries) CreateBookingSlot(ctx context.Context, arg CreateBookingSlotParams) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, createBookingSlot,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
	)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrainerID,
	)
	return i, err
}

const createDiscoveryBooking = `-- name: CreateDiscoveryBooking :one
INSERT INTO discovery_bookings (
    user_id,
    name,
    email,
    contact_mode,
    phone_number,
    selected_datetime,
    client_timezone,
    zoom_meeting_link,
    zoom_meeting_id,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    'confirmed'
)
RETURNING id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id
`

type CreateDiscoveryBookingParams struct {
	UserID           uuid.NullUUID
	Name             string
	Email            string
	ContactMode      string
	PhoneNumber      sql.NullString
	SelectedDatetime time.Time
	ClientTimezone   string
	ZoomMeetingLink  sql.NullString
	ZoomMeetingID    sql.NullString
}

func (q *Queries) CreateDiscoveryBooking(ctx context.Context, arg CreateDiscoveryBookingParams) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, createDiscoveryBooking,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.ContactMode,
		arg.PhoneNumber,
		arg.SelectedDatetime,
		arg.ClientTimezone,
		arg.ZoomMeetingLink,
		arg.ZoomMeetingID,
	)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteBookingSlot = `-- name: DeleteBookingSlot :exec
DELETE FROM booking_slots
WHERE id = $1
`

func (q *Queries) DeleteBookingSlot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBookingSlot, id)
	return err
}

const getActiveBookingSlots = `-- name: GetActiveBookingSlots :many
SELECT id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at, trainer_id FROM booking_slots
WHERE is_active = true
ORDER BY day_of_week ASC, start_time ASC
`

func (q *Queries) GetActiveBookingSlots(ctx context.Context) ([]BookingSlot, error) {
	rows, err := q.db.QueryContext(ctx, getActiveBookingSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingSlot
	for rows.Next() {
		var i BookingSlot
		if err := rows.Scan(
			&i.ID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrainerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingSlotByID = `-- name: GetBookingSlotByID :one
SELECT id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at, trainer_id FROM booking_slots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBookingSlotByID(ctx context.Context, id uuid.UUID) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, getBookingSlotByID, id)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrainerID,
	)
	return i, err
}

const getDiscoveryBookingByID = `-- name: GetDiscoveryBookingByID :one
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id FROM discovery_bookings
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDiscoveryBookingByID(ctx context.Context, id uuid.UUID) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveryBookingByID, id)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getDiscoveryBookingByUserID = `-- name: GetDiscoveryBookingByUserID :one
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id FROM discovery_bookings
WHERE user_id = $1
  AND status NOT IN ('cancelled')
LIMIT 1
`

func (q *Queries) GetDiscoveryBookingByUserID(ctx context.Context, userID uuid.NullUUID) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveryBookingByUserID, userID)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listDiscoveryBookings = `-- name: ListDiscoveryBookings :many
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id FROM discovery_bookings
ORDER BY selected_datetime ASC
`

func (q *Queries) ListDiscoveryBookings(ctx context.Context) ([]DiscoveryBooking, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveryBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryBooking
	for rows.Next() {
		var i DiscoveryBooking
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ContactMode,
			&i.PhoneNumber,
			&i.SelectedDatetime,
			&i.ClientTimezone,
			&i.ZoomMeetingLink,
			&i.ZoomMeetingID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingSlot = `-- name: UpdateBookingSlot :one
UPDATE booking_slots
SET
    day_of_week = $1,
    start_time  = $2,
    end_time    = $3,
    timezone    = $4,
    is_active   = $5,
    updated_at  = NOW()
WHERE id = $6
RETURNING id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at, trainer_id
`

type UpdateBookingSlotParams struct {
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
	IsActive  bool
	ID        uuid.UUID
}

func (q *Queries) UpdateBookingSlot(ctx context.Context, arg UpdateBookingSlotParams) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, updateBookingSlot,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
		arg.IsActive,
		arg.ID,
	)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrainerID,
	)
	return i, err
}

const updateDiscoveryBookingZoom = `-- name: UpdateDiscoveryBookingZoom :one
UPDATE discovery_bookings
SET
    zoom_meeting_link = $1,
    zoom_meeting_id   = $2,
    updated_at        = NOW()
WHERE id = $3
RETURNING id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id
`

type UpdateDiscoveryBookingZoomParams struct {
	ZoomMeetingLink sql.NullString
	ZoomMeetingID   sql.NullString
	ID              uuid.UUID
}

func (q *Queries) UpdateDiscoveryBookingZoom(ctx context.Context, arg UpdateDiscoveryBookingZoomParams) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, updateDiscoveryBookingZoom, arg.ZoomMeetingLink, arg.ZoomMeetingID, arg.ID)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
