// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkSlotConflict = `-- name: CheckSlotConflict :one
SELECT COUNT(*) FROM discovery_bookings
WHERE selected_datetime > $1::timestamptz - INTERVAL '30 minutes'
  AND selected_datetime < $1::timestamptz + INTERVAL '30 minutes'
  AND status NOT IN ('cancelled', 'completed')
`

// NOTE: assumes all discovery calls are 30 minutes; adjust interval if duration changes
func (q *Queries) CheckSlotConflict(ctx context.Context, selectedDatetime time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkSlotConflict, selectedDatetime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkSlotConflictExcluding = `-- name: CheckSlotConflictExcluding :one
SELECT COUNT(*) FROM discovery_bookings
WHERE selected_datetime > $1::timestamptz - INTERVAL '30 minutes'
  AND selected_datetime < $1::timestamptz + INTERVAL '30 minutes'
  AND status NOT IN ('cancelled', 'completed')
  AND id != $2
`

type CheckSlotConflictExcludingParams struct {
	SelectedDatetime time.Time
	ExcludeID        uuid.UUID
}

// NOTE: assumes all discovery calls are 30 minutes; adjust interval if duration changes
func (q *Queries) CheckSlotConflictExcluding(ctx context.Context, arg CheckSlotConflictExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkSlotConflictExcluding, arg.SelectedDatetime, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDiscoveryBookings = `-- name: CountDiscoveryBookings :one
SELECT COUNT(*) FROM discovery_bookings
WHERE ($1::text = '' OR status = $1::text)
`

// Pass empty string for status to count all statuses.
func (q *Queries) CountDiscoveryBookings(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDiscoveryBookings, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBookingSlot = `-- name: CreateBookingSlot :one
INSERT INTO booking_slots (
    day_of_week,
    start_time,
    end_time,
    timezone,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    true
)
RETURNING id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at, trainer_id
`

type CreateBookingSlotParams struct {
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
}

func (q *Queries) CreateBookingSlot(ctx context.Context, arg CreateBookingSlotParams) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, createBookingSlot,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
	)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrainerID,
	)
	return i, err
}

const createDiscoveryBooking = `-- name: CreateDiscoveryBooking :one
INSERT INTO discovery_bookings (
    user_id,
    name,
    email,
    contact_mode,
    phone_number,
    messenger_handle,
    selected_datetime,
    client_timezone,
    zoom_meeting_link,
    zoom_meeting_id,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    'confirmed'
)
RETURNING id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count, trainer_id, messenger_handle
`

type CreateDiscoveryBookingParams struct {
	UserID           uuid.NullUUID
	Name             string
	Email            string
	ContactMode      string
	PhoneNumber      sql.NullString
	MessengerHandle  sql.NullString
	SelectedDatetime time.Time
	ClientTimezone   string
	ZoomMeetingLink  sql.NullString
	ZoomMeetingID    sql.NullString
}

// messenger_handle is nullable — populated only when contact_mode =
// 'messenger'. zoom_meeting_link / zoom_meeting_id keep their column
// names for backward compat with existing rows but now also hold
// google_meet URLs when contact_mode = 'google_meet'. Renaming those
// columns to generic `meeting_link`/`meeting_id` is a planned cleanup
// migration that we deliberately deferred to keep this PR small.
func (q *Queries) CreateDiscoveryBooking(ctx context.Context, arg CreateDiscoveryBookingParams) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, createDiscoveryBooking,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.ContactMode,
		arg.PhoneNumber,
		arg.MessengerHandle,
		arg.SelectedDatetime,
		arg.ClientTimezone,
		arg.ZoomMeetingLink,
		arg.ZoomMeetingID,
	)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
		&i.TrainerID,
		&i.MessengerHandle,
	)
	return i, err
}

const createRescheduleHistory = `-- name: CreateRescheduleHistory :exec
INSERT INTO booking_reschedule_history (
    discovery_booking_id,
    previous_datetime,
    new_datetime,
    rescheduled_by,
    reason,
    notes
) VALUES (
    $1,
    $2::timestamptz,
    $3::timestamptz,
    $4,
    $5,
    $6
)
`

type CreateRescheduleHistoryParams struct {
	DiscoveryBookingID uuid.UUID
	PreviousDatetime   time.Time
	NewDatetime        time.Time
	RescheduledBy      string
	Reason             sql.NullString
	Notes              sql.NullString
}

func (q *Queries) CreateRescheduleHistory(ctx context.Context, arg CreateRescheduleHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createRescheduleHistory,
		arg.DiscoveryBookingID,
		arg.PreviousDatetime,
		arg.NewDatetime,
		arg.RescheduledBy,
		arg.Reason,
		arg.Notes,
	)
	return err
}

const deleteBookingSlot = `-- name: DeleteBookingSlot :exec
DELETE FROM booking_slots
WHERE id = $1
`

func (q *Queries) DeleteBookingSlot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBookingSlot, id)
	return err
}

const getActiveBookingSlots = `-- name: GetActiveBookingSlots :many
SELECT id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at, trainer_id FROM booking_slots
WHERE is_active = true
ORDER BY day_of_week ASC, start_time ASC
`

func (q *Queries) GetActiveBookingSlots(ctx context.Context) ([]BookingSlot, error) {
	rows, err := q.db.QueryContext(ctx, getActiveBookingSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingSlot
	for rows.Next() {
		var i BookingSlot
		if err := rows.Scan(
			&i.ID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrainerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveBookingSlotsForDate = `-- name: GetActiveBookingSlotsForDate :many
SELECT
    bs.id, bs.trainer_id, bs.day_of_week, bs.start_time, bs.end_time,
    bs.timezone, bs.is_active, bs.created_at, bs.updated_at
FROM booking_slots bs
WHERE bs.is_active = true
  AND bs.day_of_week = EXTRACT(DOW FROM $1::DATE)::INT
  AND NOT EXISTS (
      SELECT 1 FROM discovery_bookings db
      WHERE db.status NOT IN ('cancelled', 'completed')
        AND db.trainer_id IS NOT DISTINCT FROM bs.trainer_id
        AND (db.selected_datetime                       AT TIME ZONE COALESCE(NULLIF(bs.timezone, ''), 'UTC'))::DATE = $1::DATE
        AND (db.selected_datetime                       AT TIME ZONE COALESCE(NULLIF(bs.timezone, ''), 'UTC'))::TIME < bs.end_time
        AND ((db.selected_datetime + INTERVAL '30 minutes') AT TIME ZONE COALESCE(NULLIF(bs.timezone, ''), 'UTC'))::TIME > bs.start_time
  )
ORDER BY bs.day_of_week ASC, bs.start_time ASC
`

type GetActiveBookingSlotsForDateRow struct {
	ID        uuid.UUID
	TrainerID uuid.NullUUID
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Same as GetActiveBookingSlots filtered to a specific date and excluding
// discovery-booking slots already taken on that date. Discovery calls are
// always 30 minutes, so the conflict window is fixed.
//
// Trainer correlation: discovery_bookings.trainer_id can be NULL (slot
// not assigned yet) or set (assigned to a specific trainer). booking_slots
// has the same nullable shape: global slots have trainer_id IS NULL,
// per-trainer slots have it set. A booking conflicts with a slot only
// when their trainer_ids match — including both being NULL, which is
// what `IS NOT DISTINCT FROM` expresses. Without this guard, one
// trainer's discovery booking would falsely hide another trainer's
// (or a global) discovery slot at the same time.
//
// Timezone normalisation: bs.start_time / bs.end_time are local TIME in
// bs.timezone — convert the booking's timestamptz to that same zone
// before comparing, NOT to the booking's own client_timezone (those can
// differ and lead to off-by-hours misses).
func (q *Queries) GetActiveBookingSlotsForDate(ctx context.Context, targetDate time.Time) ([]GetActiveBookingSlotsForDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveBookingSlotsForDate, targetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveBookingSlotsForDateRow
	for rows.Next() {
		var i GetActiveBookingSlotsForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingSlotByID = `-- name: GetBookingSlotByID :one
SELECT id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at, trainer_id FROM booking_slots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBookingSlotByID(ctx context.Context, id uuid.UUID) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, getBookingSlotByID, id)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrainerID,
	)
	return i, err
}

const getDiscoveryBookingByID = `-- name: GetDiscoveryBookingByID :one
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count, trainer_id, messenger_handle FROM discovery_bookings
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDiscoveryBookingByID(ctx context.Context, id uuid.UUID) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveryBookingByID, id)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
		&i.TrainerID,
		&i.MessengerHandle,
	)
	return i, err
}

const getDiscoveryBookingByUserID = `-- name: GetDiscoveryBookingByUserID :one
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count, trainer_id, messenger_handle FROM discovery_bookings
WHERE user_id = $1
  AND status NOT IN ('cancelled')
LIMIT 1
`

func (q *Queries) GetDiscoveryBookingByUserID(ctx context.Context, userID uuid.NullUUID) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveryBookingByUserID, userID)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
		&i.TrainerID,
		&i.MessengerHandle,
	)
	return i, err
}

const getUpcomingDiscoveryBookings = `-- name: GetUpcomingDiscoveryBookings :many
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count, trainer_id, messenger_handle FROM discovery_bookings
WHERE user_id = $1
  AND selected_datetime > NOW() - INTERVAL '7 days'
  AND status NOT IN ('cancelled', 'completed')
ORDER BY selected_datetime ASC
`

// Mirror of GetUpcomingPaidSessions: keep showing the call until the user
// explicitly cancels/completes it. The 7-day grace past selected_datetime
// bounds the visibility of abandoned bookings.
func (q *Queries) GetUpcomingDiscoveryBookings(ctx context.Context, userID uuid.NullUUID) ([]DiscoveryBooking, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingDiscoveryBookings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryBooking
	for rows.Next() {
		var i DiscoveryBooking
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ContactMode,
			&i.PhoneNumber,
			&i.SelectedDatetime,
			&i.ClientTimezone,
			&i.ZoomMeetingLink,
			&i.ZoomMeetingID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.RescheduleCount,
			&i.TrainerID,
			&i.MessengerHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryBookings = `-- name: ListDiscoveryBookings :many
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count, trainer_id, messenger_handle FROM discovery_bookings
ORDER BY selected_datetime ASC
`

func (q *Queries) ListDiscoveryBookings(ctx context.Context) ([]DiscoveryBooking, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveryBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryBooking
	for rows.Next() {
		var i DiscoveryBooking
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ContactMode,
			&i.PhoneNumber,
			&i.SelectedDatetime,
			&i.ClientTimezone,
			&i.ZoomMeetingLink,
			&i.ZoomMeetingID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.RescheduleCount,
			&i.TrainerID,
			&i.MessengerHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoveryBookingsPaginated = `-- name: ListDiscoveryBookingsPaginated :many
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count, trainer_id, messenger_handle FROM discovery_bookings
WHERE ($1::text = '' OR status = $1::text)
ORDER BY selected_datetime DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListDiscoveryBookingsPaginatedParams struct {
	Status     string
	PageOffset int32
	PageLimit  int32
}

// Admin paginated view of every discovery call ever booked. Newest first so
// the most-recent activity is the top of page 1; supports
// LIMIT/OFFSET pagination matching the admin sessions endpoint.
// Pass empty string for status to return all statuses.
func (q *Queries) ListDiscoveryBookingsPaginated(ctx context.Context, arg ListDiscoveryBookingsPaginatedParams) ([]DiscoveryBooking, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveryBookingsPaginated, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryBooking
	for rows.Next() {
		var i DiscoveryBooking
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ContactMode,
			&i.PhoneNumber,
			&i.SelectedDatetime,
			&i.ClientTimezone,
			&i.ZoomMeetingLink,
			&i.ZoomMeetingID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.RescheduleCount,
			&i.TrainerID,
			&i.MessengerHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleDiscoveryBooking = `-- name: RescheduleDiscoveryBooking :one
UPDATE discovery_bookings
SET
    selected_datetime = $1::timestamptz,
    phone_number      = $2,
    zoom_meeting_link = $3,
    zoom_meeting_id   = $4,
    reschedule_count  = reschedule_count + 1,
    updated_at        = NOW()
WHERE id = $5
RETURNING id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count, trainer_id, messenger_handle
`

type RescheduleDiscoveryBookingParams struct {
	SelectedDatetime time.Time
	PhoneNumber      sql.NullString
	ZoomMeetingLink  sql.NullString
	ZoomMeetingID    sql.NullString
	ID               uuid.UUID
}

func (q *Queries) RescheduleDiscoveryBooking(ctx context.Context, arg RescheduleDiscoveryBookingParams) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, rescheduleDiscoveryBooking,
		arg.SelectedDatetime,
		arg.PhoneNumber,
		arg.ZoomMeetingLink,
		arg.ZoomMeetingID,
		arg.ID,
	)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
		&i.TrainerID,
		&i.MessengerHandle,
	)
	return i, err
}

const updateBookingSlot = `-- name: UpdateBookingSlot :one
UPDATE booking_slots
SET
    day_of_week = $1,
    start_time  = $2,
    end_time    = $3,
    timezone    = $4,
    is_active   = $5,
    updated_at  = NOW()
WHERE id = $6
RETURNING id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at, trainer_id
`

type UpdateBookingSlotParams struct {
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
	IsActive  bool
	ID        uuid.UUID
}

func (q *Queries) UpdateBookingSlot(ctx context.Context, arg UpdateBookingSlotParams) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, updateBookingSlot,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
		arg.IsActive,
		arg.ID,
	)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrainerID,
	)
	return i, err
}

const updateDiscoveryBookingZoom = `-- name: UpdateDiscoveryBookingZoom :one
UPDATE discovery_bookings
SET
    zoom_meeting_link = $1,
    zoom_meeting_id   = $2,
    updated_at        = NOW()
WHERE id = $3
RETURNING id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count, trainer_id, messenger_handle
`

type UpdateDiscoveryBookingZoomParams struct {
	ZoomMeetingLink sql.NullString
	ZoomMeetingID   sql.NullString
	ID              uuid.UUID
}

func (q *Queries) UpdateDiscoveryBookingZoom(ctx context.Context, arg UpdateDiscoveryBookingZoomParams) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, updateDiscoveryBookingZoom, arg.ZoomMeetingLink, arg.ZoomMeetingID, arg.ID)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
		&i.TrainerID,
		&i.MessengerHandle,
	)
	return i, err
}
