// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkSlotConflict = `-- name: CheckSlotConflict :one
SELECT COUNT(*) FROM discovery_bookings
WHERE selected_datetime > $1::timestamptz - INTERVAL '30 minutes'
  AND selected_datetime < $1::timestamptz + INTERVAL '30 minutes'
  AND status NOT IN ('cancelled', 'completed')
`

// NOTE: assumes all discovery calls are 30 minutes; adjust interval if duration changes
func (q *Queries) CheckSlotConflict(ctx context.Context, selectedDatetime time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkSlotConflict, selectedDatetime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkSlotConflictExcluding = `-- name: CheckSlotConflictExcluding :one
SELECT COUNT(*) FROM discovery_bookings
WHERE selected_datetime > $1::timestamptz - INTERVAL '30 minutes'
  AND selected_datetime < $1::timestamptz + INTERVAL '30 minutes'
  AND status NOT IN ('cancelled', 'completed')
  AND id != $2
`

type CheckSlotConflictExcludingParams struct {
	SelectedDatetime time.Time
	ExcludeID        uuid.UUID
}

// NOTE: assumes all discovery calls are 30 minutes; adjust interval if duration changes
func (q *Queries) CheckSlotConflictExcluding(ctx context.Context, arg CheckSlotConflictExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkSlotConflictExcluding, arg.SelectedDatetime, arg.ExcludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBookingSlot = `-- name: CreateBookingSlot :one
INSERT INTO booking_slots (
    day_of_week,
    start_time,
    end_time,
    timezone,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    true
)
RETURNING id, trainer_id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at
`

type CreateBookingSlotParams struct {
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
}

func (q *Queries) CreateBookingSlot(ctx context.Context, arg CreateBookingSlotParams) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, createBookingSlot,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
	)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDiscoveryBooking = `-- name: CreateDiscoveryBooking :one
INSERT INTO discovery_bookings (
    user_id,
    name,
    email,
    contact_mode,
    phone_number,
    selected_datetime,
    client_timezone,
    zoom_meeting_link,
    zoom_meeting_id,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    'confirmed'
)
RETURNING id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count
`

type CreateDiscoveryBookingParams struct {
	UserID           uuid.NullUUID
	Name             string
	Email            string
	ContactMode      string
	PhoneNumber      sql.NullString
	SelectedDatetime time.Time
	ClientTimezone   string
	ZoomMeetingLink  sql.NullString
	ZoomMeetingID    sql.NullString
}

func (q *Queries) CreateDiscoveryBooking(ctx context.Context, arg CreateDiscoveryBookingParams) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, createDiscoveryBooking,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.ContactMode,
		arg.PhoneNumber,
		arg.SelectedDatetime,
		arg.ClientTimezone,
		arg.ZoomMeetingLink,
		arg.ZoomMeetingID,
	)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
	)
	return i, err
}

const createRescheduleHistory = `-- name: CreateRescheduleHistory :exec
INSERT INTO booking_reschedule_history (
    discovery_booking_id,
    previous_datetime,
    new_datetime,
    rescheduled_by,
    reason,
    notes
) VALUES (
    $1,
    $2::timestamptz,
    $3::timestamptz,
    $4,
    $5,
    $6
)
`

type CreateRescheduleHistoryParams struct {
	DiscoveryBookingID uuid.UUID
	PreviousDatetime   time.Time
	NewDatetime        time.Time
	RescheduledBy      string
	Reason             sql.NullString
	Notes              sql.NullString
}

func (q *Queries) CreateRescheduleHistory(ctx context.Context, arg CreateRescheduleHistoryParams) error {
	_, err := q.db.ExecContext(ctx, createRescheduleHistory,
		arg.DiscoveryBookingID,
		arg.PreviousDatetime,
		arg.NewDatetime,
		arg.RescheduledBy,
		arg.Reason,
		arg.Notes,
	)
	return err
}

const deleteBookingSlot = `-- name: DeleteBookingSlot :exec
DELETE FROM booking_slots
WHERE id = $1
`

func (q *Queries) DeleteBookingSlot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBookingSlot, id)
	return err
}

const getActiveBookingSlots = `-- name: GetActiveBookingSlots :many
SELECT id, trainer_id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at FROM booking_slots
WHERE is_active = true
ORDER BY day_of_week ASC, start_time ASC
`

func (q *Queries) GetActiveBookingSlots(ctx context.Context) ([]BookingSlot, error) {
	rows, err := q.db.QueryContext(ctx, getActiveBookingSlots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingSlot
	for rows.Next() {
		var i BookingSlot
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookingSlotByID = `-- name: GetBookingSlotByID :one
SELECT id, trainer_id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at FROM booking_slots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBookingSlotByID(ctx context.Context, id uuid.UUID) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, getBookingSlotByID, id)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiscoveryBookingByID = `-- name: GetDiscoveryBookingByID :one
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count FROM discovery_bookings
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDiscoveryBookingByID(ctx context.Context, id uuid.UUID) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveryBookingByID, id)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
	)
	return i, err
}

const getDiscoveryBookingByUserID = `-- name: GetDiscoveryBookingByUserID :one
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count FROM discovery_bookings
WHERE user_id = $1
  AND status NOT IN ('cancelled')
LIMIT 1
`

func (q *Queries) GetDiscoveryBookingByUserID(ctx context.Context, userID uuid.NullUUID) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, getDiscoveryBookingByUserID, userID)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
	)
	return i, err
}

const listDiscoveryBookings = `-- name: ListDiscoveryBookings :many
SELECT id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count FROM discovery_bookings
ORDER BY selected_datetime ASC
`

func (q *Queries) ListDiscoveryBookings(ctx context.Context) ([]DiscoveryBooking, error) {
	rows, err := q.db.QueryContext(ctx, listDiscoveryBookings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiscoveryBooking
	for rows.Next() {
		var i DiscoveryBooking
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.ContactMode,
			&i.PhoneNumber,
			&i.SelectedDatetime,
			&i.ClientTimezone,
			&i.ZoomMeetingLink,
			&i.ZoomMeetingID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.RescheduleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleDiscoveryBooking = `-- name: RescheduleDiscoveryBooking :one
UPDATE discovery_bookings
SET
    selected_datetime = $1::timestamptz,
    phone_number      = $2,
    zoom_meeting_link = $3,
    zoom_meeting_id   = $4,
    reschedule_count  = reschedule_count + 1,
    updated_at        = NOW()
WHERE id = $5
RETURNING id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count
`

type RescheduleDiscoveryBookingParams struct {
	SelectedDatetime time.Time
	PhoneNumber      sql.NullString
	ZoomMeetingLink  sql.NullString
	ZoomMeetingID    sql.NullString
	ID               uuid.UUID
}

func (q *Queries) RescheduleDiscoveryBooking(ctx context.Context, arg RescheduleDiscoveryBookingParams) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, rescheduleDiscoveryBooking,
		arg.SelectedDatetime,
		arg.PhoneNumber,
		arg.ZoomMeetingLink,
		arg.ZoomMeetingID,
		arg.ID,
	)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
	)
	return i, err
}

const updateBookingSlot = `-- name: UpdateBookingSlot :one
UPDATE booking_slots
SET
    day_of_week = $1,
    start_time  = $2,
    end_time    = $3,
    timezone    = $4,
    is_active   = $5,
    updated_at  = NOW()
WHERE id = $6
RETURNING id, trainer_id, day_of_week, start_time, end_time, timezone, is_active, created_at, updated_at
`

type UpdateBookingSlotParams struct {
	DayOfWeek int16
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
	IsActive  bool
	ID        uuid.UUID
}

func (q *Queries) UpdateBookingSlot(ctx context.Context, arg UpdateBookingSlotParams) (BookingSlot, error) {
	row := q.db.QueryRowContext(ctx, updateBookingSlot,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
		arg.IsActive,
		arg.ID,
	)
	var i BookingSlot
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDiscoveryBookingZoom = `-- name: UpdateDiscoveryBookingZoom :one
UPDATE discovery_bookings
SET
    zoom_meeting_link = $1,
    zoom_meeting_id   = $2,
    updated_at        = NOW()
WHERE id = $3
RETURNING id, name, email, contact_mode, phone_number, selected_datetime, client_timezone, zoom_meeting_link, zoom_meeting_id, status, created_at, updated_at, user_id, reschedule_count
`

type UpdateDiscoveryBookingZoomParams struct {
	ZoomMeetingLink sql.NullString
	ZoomMeetingID   sql.NullString
	ID              uuid.UUID
}

func (q *Queries) UpdateDiscoveryBookingZoom(ctx context.Context, arg UpdateDiscoveryBookingZoomParams) (DiscoveryBooking, error) {
	row := q.db.QueryRowContext(ctx, updateDiscoveryBookingZoom, arg.ZoomMeetingLink, arg.ZoomMeetingID, arg.ID)
	var i DiscoveryBooking
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ContactMode,
		&i.PhoneNumber,
		&i.SelectedDatetime,
		&i.ClientTimezone,
		&i.ZoomMeetingLink,
		&i.ZoomMeetingID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.RescheduleCount,
	)
	return i, err
}
