// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery_bookings.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDiscoveryBooking = `-- name: CreateDiscoveryBooking :one
INSERT INTO bookings (
  trainer_id,
  client_id,
  subscription_id,
  calendly_event_id,
  scheduled_start,
  scheduled_end,
  timezone,
  booking_status,
  session_platform,
  cancellation_reason,
  created_at,
  cancelled_at,
  is_discovery_call,
  meeting_join_url,
  meeting_start_url
) VALUES (
  $1,
  $2,
  NULL,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  true,
  $12,
  $13
)
RETURNING
  id,
  trainer_id,
  client_id,
  subscription_id,
  calendly_event_id,
  scheduled_start,
  scheduled_end,
  timezone,
  booking_status,
  session_platform,
  cancellation_reason,
  created_at,
  cancelled_at,
  is_discovery_call,
  meeting_join_url,
  meeting_start_url
`

type CreateDiscoveryBookingParams struct {
	TrainerID          uuid.UUID
	ClientID           uuid.UUID
	CalendlyEventID    sql.NullString
	ScheduledStart     sql.NullTime
	ScheduledEnd       sql.NullTime
	Timezone           sql.NullString
	BookingStatus      sql.NullString
	SessionPlatform    sql.NullString
	CancellationReason sql.NullString
	CreatedAt          sql.NullTime
	CancelledAt        sql.NullTime
	MeetingJoinUrl     sql.NullString
	MeetingStartUrl    sql.NullString
}

func (q *Queries) CreateDiscoveryBooking(ctx context.Context, arg CreateDiscoveryBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createDiscoveryBooking,
		arg.TrainerID,
		arg.ClientID,
		arg.CalendlyEventID,
		arg.ScheduledStart,
		arg.ScheduledEnd,
		arg.Timezone,
		arg.BookingStatus,
		arg.SessionPlatform,
		arg.CancellationReason,
		arg.CreatedAt,
		arg.CancelledAt,
		arg.MeetingJoinUrl,
		arg.MeetingStartUrl,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.ClientID,
		&i.SubscriptionID,
		&i.CalendlyEventID,
		&i.ScheduledStart,
		&i.ScheduledEnd,
		&i.Timezone,
		&i.BookingStatus,
		&i.SessionPlatform,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.IsDiscoveryCall,
		&i.MeetingJoinUrl,
		&i.MeetingStartUrl,
	)
	return i, err
}

const hasDiscoveryBookingForClientTrainer = `-- name: HasDiscoveryBookingForClientTrainer :one
SELECT EXISTS (
  SELECT 1
  FROM bookings
  WHERE trainer_id = $1
    AND client_id = $2
    AND is_discovery_call = true
) AS has_discovery_booking
`

type HasDiscoveryBookingForClientTrainerParams struct {
	TrainerID uuid.UUID
	ClientID  uuid.UUID
}

func (q *Queries) HasDiscoveryBookingForClientTrainer(ctx context.Context, arg HasDiscoveryBookingForClientTrainerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasDiscoveryBookingForClientTrainer, arg.TrainerID, arg.ClientID)
	var has_discovery_booking bool
	err := row.Scan(&has_discovery_booking)
	return has_discovery_booking, err
}
