// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: failed_video_uploads.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const recordFailedVideoUpload = `-- name: RecordFailedVideoUpload :exec
INSERT INTO failed_video_uploads (trainer_id, object_key, attempts, last_error)
VALUES ($1, $2, $3, $4)
`

type RecordFailedVideoUploadParams struct {
	TrainerID uuid.UUID
	ObjectKey string
	Attempts  int32
	LastError string
}

// Persists a terminally-failed trainer-intro-video upload so the failure is
// queryable. The temp files are gone by the time we get here — this row is
// for visibility/ops only, not a re-run queue.
func (q *Queries) RecordFailedVideoUpload(ctx context.Context, arg RecordFailedVideoUploadParams) error {
	_, err := q.db.ExecContext(ctx, recordFailedVideoUpload,
		arg.TrainerID,
		arg.ObjectKey,
		arg.Attempts,
		arg.LastError,
	)
	return err
}
