// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: failed_avatar_uploads.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const recordFailedAvatarUpload = `-- name: RecordFailedAvatarUpload :exec
INSERT INTO failed_avatar_uploads (user_id, object_key, attempts, last_error)
VALUES ($1, $2, $3, $4)
`

type RecordFailedAvatarUploadParams struct {
	UserID    uuid.UUID
	ObjectKey string
	Attempts  int32
	LastError string
}

// Persists a terminally-failed avatar upload so the failure is queryable.
// The bytes themselves are gone — this row is for visibility/ops only.
func (q *Queries) RecordFailedAvatarUpload(ctx context.Context, arg RecordFailedAvatarUploadParams) error {
	_, err := q.db.ExecContext(ctx, recordFailedAvatarUpload,
		arg.UserID,
		arg.ObjectKey,
		arg.Attempts,
		arg.LastError,
	)
	return err
}
