// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feature_flags.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getFeatureFlag = `-- name: GetFeatureFlag :one
SELECT key, enabled, updated_by, notes, created_at, updated_at
FROM feature_flags
WHERE key = $1
`

func (q *Queries) GetFeatureFlag(ctx context.Context, key string) (FeatureFlag, error) {
	row := q.db.QueryRowContext(ctx, getFeatureFlag, key)
	var i FeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Enabled,
		&i.UpdatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT key, enabled, updated_by, notes, created_at, updated_at
FROM feature_flags
ORDER BY key ASC
`

// Ordered by key for stable response shape — both the public read and
// the admin list endpoint depend on this for deterministic JSON output.
func (q *Queries) ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.QueryContext(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureFlag
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.Key,
			&i.Enabled,
			&i.UpdatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeatureFlag = `-- name: UpsertFeatureFlag :one
INSERT INTO feature_flags (key, enabled, updated_by, notes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO UPDATE
SET enabled    = EXCLUDED.enabled,
    updated_by = EXCLUDED.updated_by,
    notes      = EXCLUDED.notes,
    updated_at = NOW()
RETURNING key, enabled, updated_by, notes, created_at, updated_at
`

type UpsertFeatureFlagParams struct {
	Key       string
	Enabled   bool
	UpdatedBy uuid.NullUUID
	Notes     sql.NullString
}

// Single-statement write: insert if missing, update if present. Admin
// UI calls this when an operator flips a flag — having one entry point
// avoids a TOCTOU race between "does this flag exist yet" and "now
// update it".
func (q *Queries) UpsertFeatureFlag(ctx context.Context, arg UpsertFeatureFlagParams) (FeatureFlag, error) {
	row := q.db.QueryRowContext(ctx, upsertFeatureFlag,
		arg.Key,
		arg.Enabled,
		arg.UpdatedBy,
		arg.Notes,
	)
	var i FeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Enabled,
		&i.UpdatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
