// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login_security.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getLoginSecurityByUserID = `-- name: GetLoginSecurityByUserID :one
SELECT user_id, failed_attempts, locked_until, last_failed_at, updated_at, created_at
FROM login_security
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetLoginSecurityByUserID(ctx context.Context, userID uuid.UUID) (LoginSecurity, error) {
	row := q.db.QueryRowContext(ctx, getLoginSecurityByUserID, userID)
	var i LoginSecurity
	err := row.Scan(
		&i.UserID,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastFailedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementFailedLoginAttempt = `-- name: IncrementFailedLoginAttempt :one
UPDATE login_security
SET failed_attempts = failed_attempts + 1,
    last_failed_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, failed_attempts, locked_until, last_failed_at, updated_at, created_at
`

func (q *Queries) IncrementFailedLoginAttempt(ctx context.Context, userID uuid.UUID) (LoginSecurity, error) {
	row := q.db.QueryRowContext(ctx, incrementFailedLoginAttempt, userID)
	var i LoginSecurity
	err := row.Scan(
		&i.UserID,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastFailedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockUserLoginUntil = `-- name: LockUserLoginUntil :one
UPDATE login_security
SET locked_until = $2,
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, failed_attempts, locked_until, last_failed_at, updated_at, created_at
`

type LockUserLoginUntilParams struct {
	UserID      uuid.UUID
	LockedUntil sql.NullTime
}

func (q *Queries) LockUserLoginUntil(ctx context.Context, arg LockUserLoginUntilParams) (LoginSecurity, error) {
	row := q.db.QueryRowContext(ctx, lockUserLoginUntil, arg.UserID, arg.LockedUntil)
	var i LoginSecurity
	err := row.Scan(
		&i.UserID,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastFailedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const resetLoginSecurityOnSuccess = `-- name: ResetLoginSecurityOnSuccess :exec
UPDATE login_security
SET failed_attempts = 0,
    locked_until = NULL,
    last_failed_at = NULL,
    updated_at = NOW()
WHERE user_id = $1
`

func (q *Queries) ResetLoginSecurityOnSuccess(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetLoginSecurityOnSuccess, userID)
	return err
}

const upsertLoginSecurityRow = `-- name: UpsertLoginSecurityRow :one
INSERT INTO login_security (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE
  SET updated_at = NOW()
RETURNING user_id, failed_attempts, locked_until, last_failed_at, updated_at, created_at
`

func (q *Queries) UpsertLoginSecurityRow(ctx context.Context, userID uuid.UUID) (LoginSecurity, error) {
	row := q.db.QueryRowContext(ctx, upsertLoginSecurityRow, userID)
	var i LoginSecurity
	err := row.Scan(
		&i.UserID,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastFailedAt,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
