// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	Password     sql.NullString
	AuthProvider string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type VerificationCode struct {
	ID        uuid.UUID
	Email     string
	Code      string
	CreatedAt time.Time
	ExpiresAt time.Time
}
