// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AdminInvite struct {
	ID         uuid.UUID
	Email      string
	Name       string
	TokenHash  string
	InvitedBy  uuid.UUID
	ExpiresAt  time.Time
	AcceptedAt sql.NullTime
	RevokedAt  sql.NullTime
	CreatedAt  time.Time
}

type Role struct {
	ID       uuid.UUID
	Name     string
	CratedAt time.Time
}

type Session struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash sql.NullString
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsVerified   bool
	Timezone     string
	LastLogin    sql.NullTime
	DeletedAt    sql.NullTime
}

type UserRole struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt time.Time
}

type VerificationCode struct {
	ID        uuid.UUID
	Email     string
	Code      string
	CreatedAt time.Time
	ExpiresAt time.Time
}
