// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countNotification = `-- name: CountNotification :one
SELECT COUNT(*) FROM notification WHERE user_id=$1
`

func (q *Queries) CountNotification(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotification, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT
INTO notification (user_id, title, message, idempotency_key) 
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, message, type, status, idempotency_key, retry_count, sent_at, created_at, updated_at
`

type CreateNotificationParams struct {
	UserID         uuid.UUID
	Title          string
	Message        string
	IdempotencyKey string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.IdempotencyKey,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotificationWithType = `-- name: CreateNotificationWithType :one
INSERT INTO 
notification (user_id, title, message, idempotency_key, type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, message, type, status, idempotency_key, retry_count, sent_at, created_at, updated_at
`

type CreateNotificationWithTypeParams struct {
	UserID         uuid.UUID
	Title          string
	Message        string
	IdempotencyKey string
	Type           string
}

func (q *Queries) CreateNotificationWithType(ctx context.Context, arg CreateNotificationWithTypeParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotificationWithType,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.IdempotencyKey,
		arg.Type,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT 
    id,
    user_id,
    title,
    message,
    type,
    status,
    idempotency_key,
    retry_count,
    sent_at,
    created_at,
    updated_at
FROM notification
WHERE id=$1
LIMIT 1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationByStatus = `-- name: GetNotificationByStatus :many
SELECT 
    id,
    user_id,
    title,
    message,
    type,
    status,
    idempotency_key,
    retry_count,
    sent_at,
    created_at,
    updated_at
FROM notification
WHERE status=$1
`

func (q *Queries) GetNotificationByStatus(ctx context.Context, status string) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Status,
			&i.IdempotencyKey,
			&i.RetryCount,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationByUserID = `-- name: GetNotificationByUserID :many
SELECT 
    id,
    user_id,
    title,
    message,
    type,
    status,
    idempotency_key,
    retry_count,
    sent_at,
    created_at,
    updated_at
FROM notification
WHERE user_id=$1
`

func (q *Queries) GetNotificationByUserID(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Status,
			&i.IdempotencyKey,
			&i.RetryCount,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingRealTimeNotification = `-- name: GetPendingRealTimeNotification :many
SELECT 
    id, user_id, title, message, type, status, idempotency_key,
    retry_count, sent_at, created_at, updated_at
    FROM notification
    WHERE user_id = $1 AND type = 'realtime' AND status = 'pending'
    ORDER BY created_at ASC
`

func (q *Queries) GetPendingRealTimeNotification(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getPendingRealTimeNotification, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Status,
			&i.IdempotencyKey,
			&i.RetryCount,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSingleUserNotification = `-- name: GetSingleUserNotification :one
SELECT 
    id,
    user_id,
    title,
    message,
    type,
    status,
    idempotency_key,
    retry_count,
    sent_at,
    created_at,
    updated_at
FROM notification
WHERE id=$1 AND user_id=$2
LIMIT 1
`

type GetSingleUserNotificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSingleUserNotification(ctx context.Context, arg GetSingleUserNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getSingleUserNotification, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Status,
		&i.IdempotencyKey,
		&i.RetryCount,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserNotification = `-- name: GetUserNotification :many
SELECT 
    id,
    user_id,
    title,
    message,
    type,
    status,
    idempotency_key,
    retry_count,
    sent_at,
    created_at,
    updated_at
FROM notification
WHERE user_id=$1
ORDER BY created_at DESC
`

func (q *Queries) GetUserNotification(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, getUserNotification, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Status,
			&i.IdempotencyKey,
			&i.RetryCount,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notification
SET status=$1, 
    retry_count=CASE WHEN $1 = 'failed' THEN retry_count + 1 ELSE retry_count END,
    sent_at=CASE WHEN $1 = 'sent' THEN NOW() ELSE sent_at END,
    updated_at=NOW()
WHERE id=$2
`

type UpdateNotificationStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateNotificationStatus, arg.Status, arg.ID)
	return err
}
