// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisation_media.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countOrganisationMedia = `-- name: CountOrganisationMedia :one
SELECT COUNT(*) FROM organisation_media
WHERE ($1::text = '' OR media_type = $1::text)
  AND ($2::text   = '' OR category   = $2::text)
  AND ($3::text     = '' OR status     = $3::text)
`

type CountOrganisationMediaParams struct {
	MediaType string
	Category  string
	Status    string
}

// Total count for ListOrganisationMedia, applying the same filters so
// pagination meta matches the body length.
func (q *Queries) CountOrganisationMedia(ctx context.Context, arg CountOrganisationMediaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrganisationMedia, arg.MediaType, arg.Category, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganisationMedia = `-- name: CreateOrganisationMedia :one
INSERT INTO organisation_media (
    media_type,
    title,
    description,
    category,
    object_key,
    public_url,
    mime_type,
    size_bytes,
    uploaded_by
) VALUES (
    $1,
    $2,
    NULLIF($3::text, ''),
    NULLIF($4::text, ''),
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, media_type, title, description, category, object_key, public_url, mime_type, size_bytes, uploaded_by, status, created_at, updated_at
`

type CreateOrganisationMediaParams struct {
	MediaType   string
	Title       string
	Description string
	Category    string
	ObjectKey   string
	PublicUrl   string
	MimeType    string
	SizeBytes   int64
	UploadedBy  uuid.NullUUID
}

// POST /media/{images,videos} writes the row with status='processing'
// (the default) and hands the worker an upload job. Status is flipped
// to 'ready' (or 'failed') by the worker after the upload + transcode
// complete. The object_key + public_url are computed at handler time
// and stay stable for the lifetime of the row — the worker writes to
// exactly the key we already wrote into the DB.
func (q *Queries) CreateOrganisationMedia(ctx context.Context, arg CreateOrganisationMediaParams) (OrganisationMedium, error) {
	row := q.db.QueryRowContext(ctx, createOrganisationMedia,
		arg.MediaType,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.ObjectKey,
		arg.PublicUrl,
		arg.MimeType,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i OrganisationMedium
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ObjectKey,
		&i.PublicUrl,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrganisationMedia = `-- name: DeleteOrganisationMedia :one
DELETE FROM organisation_media WHERE id = $1 RETURNING id, media_type, title, description, category, object_key, public_url, mime_type, size_bytes, uploaded_by, status, created_at, updated_at
`

// Returns the deleted row so the handler can pull the object_key and
// remove the underlying MinIO object — without this, deletes would
// orphan files in storage.
func (q *Queries) DeleteOrganisationMedia(ctx context.Context, id uuid.UUID) (OrganisationMedium, error) {
	row := q.db.QueryRowContext(ctx, deleteOrganisationMedia, id)
	var i OrganisationMedium
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ObjectKey,
		&i.PublicUrl,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganisationMediaByID = `-- name: GetOrganisationMediaByID :one
SELECT id, media_type, title, description, category, object_key, public_url, mime_type, size_bytes, uploaded_by, status, created_at, updated_at FROM organisation_media WHERE id = $1
`

func (q *Queries) GetOrganisationMediaByID(ctx context.Context, id uuid.UUID) (OrganisationMedium, error) {
	row := q.db.QueryRowContext(ctx, getOrganisationMediaByID, id)
	var i OrganisationMedium
	err := row.Scan(
		&i.ID,
		&i.MediaType,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.ObjectKey,
		&i.PublicUrl,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganisationMedia = `-- name: ListOrganisationMedia :many
SELECT id, media_type, title, description, category, object_key, public_url, mime_type, size_bytes, uploaded_by, status, created_at, updated_at FROM organisation_media
WHERE ($1::text = '' OR media_type = $1::text)
  AND ($2::text   = '' OR category   = $2::text)
  AND ($3::text     = '' OR status     = $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $5
OFFSET $4
`

type ListOrganisationMediaParams struct {
	MediaType  string
	Category   string
	Status     string
	PageOffset int32
	PageLimit  int32
}

// Public list with optional filters. Empty-string sentinels for
// media_type / category mean "no filter" — keeps the handler signature
// simple (a missing query param maps to "") without forcing dynamic
// query construction. status defaults to 'ready' so callers don't see
// half-uploaded rows; the admin endpoint can pass status=” to see
// everything including in-flight + failed.
func (q *Queries) ListOrganisationMedia(ctx context.Context, arg ListOrganisationMediaParams) ([]OrganisationMedium, error) {
	rows, err := q.db.QueryContext(ctx, listOrganisationMedia,
		arg.MediaType,
		arg.Category,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganisationMedium
	for rows.Next() {
		var i OrganisationMedium
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.ObjectKey,
			&i.PublicUrl,
			&i.MimeType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganisationMediaStatus = `-- name: UpdateOrganisationMediaStatus :execrows
UPDATE organisation_media
SET status = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateOrganisationMediaStatusParams struct {
	Status string
	ID     uuid.UUID
}

// Worker-only — flips status to 'ready' (success) or 'failed' (after
// retries exhausted). Returns rowsAffected so the worker can
// distinguish "wrote OK" from "row was deleted while we were
// processing" and skip emitting a misleading success log.
func (q *Queries) UpdateOrganisationMediaStatus(ctx context.Context, arg UpdateOrganisationMediaStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOrganisationMediaStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
