// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const consumePasswordResetCode = `-- name: ConsumePasswordResetCode :one
DELETE FROM password_reset_codes
WHERE email = $1 AND code = $2 AND expires_at > NOW()
RETURNING id, email, code, created_at, expires_at
`

type ConsumePasswordResetCodeParams struct {
	Email string
	Code  string
}

func (q *Queries) ConsumePasswordResetCode(ctx context.Context, arg ConsumePasswordResetCodeParams) (PasswordResetCode, error) {
	row := q.db.QueryRowContext(ctx, consumePasswordResetCode, arg.Email, arg.Code)
	var i PasswordResetCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deletePasswordResetCodes = `-- name: DeletePasswordResetCodes :exec
DELETE FROM password_reset_codes WHERE email = $1
`

func (q *Queries) DeletePasswordResetCodes(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetCodes, email)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users SET password = $2, updated_at = NOW()
WHERE email = $1 AND auth_provider = 'local' AND is_active = true
RETURNING id, email, name, password, auth_provider, is_active, created_at, updated_at, role, gender, fitness_goals, fitness_level, avatar_url, phone_number, apple_user_id
`

type UpdateUserPasswordParams struct {
	Email    string
	Password sql.NullString
}

// The is_active = true filter is defense-in-depth: even if the handler's
// pre-check passes, this statement returns no rows for an inactive account
// (e.g. if the account is deactivated mid-flow), and the caller surfaces a
// generic invalid-code error.
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPassword, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.Gender,
		pq.Array(&i.FitnessGoals),
		&i.FitnessLevel,
		&i.AvatarUrl,
		&i.PhoneNumber,
		&i.AppleUserID,
	)
	return i, err
}

const upsertPasswordResetCode = `-- name: UpsertPasswordResetCode :exec
INSERT INTO password_reset_codes (email, code, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (email) DO UPDATE
    SET code       = EXCLUDED.code,
        expires_at = EXCLUDED.expires_at,
        created_at = NOW()
`

type UpsertPasswordResetCodeParams struct {
	Email     string
	Code      string
	ExpiresAt time.Time
}

// Atomically replaces any prior code for the email. Combined with the
// UNIQUE(email) constraint on password_reset_codes, this guarantees at most
// one valid code per email at any time.
func (q *Queries) UpsertPasswordResetCode(ctx context.Context, arg UpsertPasswordResetCodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertPasswordResetCode, arg.Email, arg.Code, arg.ExpiresAt)
	return err
}

const verifyPasswordResetCode = `-- name: VerifyPasswordResetCode :one
SELECT id, email, code, created_at, expires_at FROM password_reset_codes
WHERE email = $1 AND code = $2 AND expires_at > NOW()
`

type VerifyPasswordResetCodeParams struct {
	Email string
	Code  string
}

// Read-only check: confirms the code is valid and not expired without consuming it.
// Used by the verify-otp step so mobile can confirm the code before showing the new-password screen.
func (q *Queries) VerifyPasswordResetCode(ctx context.Context, arg VerifyPasswordResetCodeParams) (PasswordResetCode, error) {
	row := q.db.QueryRowContext(ctx, verifyPasswordResetCode, arg.Email, arg.Code)
	var i PasswordResetCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
