// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const confirmPayment = `-- name: ConfirmPayment :one
UPDATE payments
SET
  payment_status          = 'successful',
  provider_transaction_id = $1,
  paid_at                 = NOW()
WHERE id = $2
    AND payment_status = 'pending'
RETURNING
  id,
  subscription_id,
  booking_id,
  payer_id,
  provider,
  provider_transaction_id,
  idempotency_key,
  currency,
  total_amount,
  trainer_earning,
  platform_fee,
  payment_type,
  payment_status,
  paid_at,
  created_at
`

type ConfirmPaymentParams struct {
	ProviderTransactionID sql.NullString
	ID                    uuid.UUID
}

type ConfirmPaymentRow struct {
	ID                    uuid.UUID
	SubscriptionID        uuid.NullUUID
	BookingID             uuid.NullUUID
	PayerID               uuid.UUID
	Provider              string
	ProviderTransactionID sql.NullString
	IdempotencyKey        string
	Currency              string
	TotalAmount           int64
	TrainerEarning        int64
	PlatformFee           int64
	PaymentType           string
	PaymentStatus         string
	PaidAt                sql.NullTime
	CreatedAt             time.Time
}

func (q *Queries) ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) (ConfirmPaymentRow, error) {
	row := q.db.QueryRowContext(ctx, confirmPayment, arg.ProviderTransactionID, arg.ID)
	var i ConfirmPaymentRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.BookingID,
		&i.PayerID,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.IdempotencyKey,
		&i.Currency,
		&i.TotalAmount,
		&i.TrainerEarning,
		&i.PlatformFee,
		&i.PaymentType,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  subscription_id,
  booking_id,
  payer_id,
  provider,
  provider_transaction_id,
  idempotency_key,
  currency,
  total_amount,
  trainer_earning,
  platform_fee,
  payment_type,
  payment_status
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12
)
RETURNING
  id,
  subscription_id,
  booking_id,
  payer_id,
  provider,
  provider_transaction_id,
  idempotency_key,
  currency,
  total_amount,
  trainer_earning,
  platform_fee,
  payment_type,
  payment_status,
  paid_at,
  created_at
`

type CreatePaymentParams struct {
	SubscriptionID        uuid.NullUUID
	BookingID             uuid.NullUUID
	PayerID               uuid.UUID
	Provider              string
	ProviderTransactionID sql.NullString
	IdempotencyKey        string
	Currency              string
	TotalAmount           int64
	TrainerEarning        int64
	PlatformFee           int64
	PaymentType           string
	PaymentStatus         string
}

type CreatePaymentRow struct {
	ID                    uuid.UUID
	SubscriptionID        uuid.NullUUID
	BookingID             uuid.NullUUID
	PayerID               uuid.UUID
	Provider              string
	ProviderTransactionID sql.NullString
	IdempotencyKey        string
	Currency              string
	TotalAmount           int64
	TrainerEarning        int64
	PlatformFee           int64
	PaymentType           string
	PaymentStatus         string
	PaidAt                sql.NullTime
	CreatedAt             time.Time
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.SubscriptionID,
		arg.BookingID,
		arg.PayerID,
		arg.Provider,
		arg.ProviderTransactionID,
		arg.IdempotencyKey,
		arg.Currency,
		arg.TotalAmount,
		arg.TrainerEarning,
		arg.PlatformFee,
		arg.PaymentType,
		arg.PaymentStatus,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.BookingID,
		&i.PayerID,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.IdempotencyKey,
		&i.Currency,
		&i.TotalAmount,
		&i.TrainerEarning,
		&i.PlatformFee,
		&i.PaymentType,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const failPayment = `-- name: FailPayment :one
UPDATE payments
SET payment_status = 'failed'
WHERE id = $1
    AND payment_status = 'pending'
RETURNING
  id,
  subscription_id,
  booking_id,
  payer_id,
  provider,
  provider_transaction_id,
  idempotency_key,
  currency,
  total_amount,
  trainer_earning,
  platform_fee,
  payment_type,
  payment_status,
  paid_at,
  created_at
`

type FailPaymentRow struct {
	ID                    uuid.UUID
	SubscriptionID        uuid.NullUUID
	BookingID             uuid.NullUUID
	PayerID               uuid.UUID
	Provider              string
	ProviderTransactionID sql.NullString
	IdempotencyKey        string
	Currency              string
	TotalAmount           int64
	TrainerEarning        int64
	PlatformFee           int64
	PaymentType           string
	PaymentStatus         string
	PaidAt                sql.NullTime
	CreatedAt             time.Time
}

func (q *Queries) FailPayment(ctx context.Context, id uuid.UUID) (FailPaymentRow, error) {
	row := q.db.QueryRowContext(ctx, failPayment, id)
	var i FailPaymentRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.BookingID,
		&i.PayerID,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.IdempotencyKey,
		&i.Currency,
		&i.TotalAmount,
		&i.TrainerEarning,
		&i.PlatformFee,
		&i.PaymentType,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
  id,
  subscription_id,
  booking_id,
  payer_id,
  provider,
  provider_transaction_id,
  idempotency_key,
  currency,
  total_amount,
  trainer_earning,
  platform_fee,
  payment_type,
  payment_status,
  paid_at,
  created_at
FROM payments
WHERE id = $1
LIMIT 1
`

type GetPaymentByIDRow struct {
	ID                    uuid.UUID
	SubscriptionID        uuid.NullUUID
	BookingID             uuid.NullUUID
	PayerID               uuid.UUID
	Provider              string
	ProviderTransactionID sql.NullString
	IdempotencyKey        string
	Currency              string
	TotalAmount           int64
	TrainerEarning        int64
	PlatformFee           int64
	PaymentType           string
	PaymentStatus         string
	PaidAt                sql.NullTime
	CreatedAt             time.Time
}

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (GetPaymentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.BookingID,
		&i.PayerID,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.IdempotencyKey,
		&i.Currency,
		&i.TotalAmount,
		&i.TrainerEarning,
		&i.PlatformFee,
		&i.PaymentType,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT
  id,
  subscription_id,
  booking_id,
  payer_id,
  provider,
  provider_transaction_id,
  idempotency_key,
  currency,
  total_amount,
  trainer_earning,
  platform_fee,
  payment_type,
  payment_status,
  paid_at,
  created_at
FROM payments
WHERE payer_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListPaymentsParams struct {
	PayerID uuid.UUID
	Limit   int32
	Offset  int32
}

type ListPaymentsRow struct {
	ID                    uuid.UUID
	SubscriptionID        uuid.NullUUID
	BookingID             uuid.NullUUID
	PayerID               uuid.UUID
	Provider              string
	ProviderTransactionID sql.NullString
	IdempotencyKey        string
	Currency              string
	TotalAmount           int64
	TrainerEarning        int64
	PlatformFee           int64
	PaymentType           string
	PaymentStatus         string
	PaidAt                sql.NullTime
	CreatedAt             time.Time
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]ListPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPayments, arg.PayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsRow
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.BookingID,
			&i.PayerID,
			&i.Provider,
			&i.ProviderTransactionID,
			&i.IdempotencyKey,
			&i.Currency,
			&i.TotalAmount,
			&i.TrainerEarning,
			&i.PlatformFee,
			&i.PaymentType,
			&i.PaymentStatus,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
