// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
  booking_id,
  trainer_id,
  client_user_id,
  rating,
  review
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  booking_id,
  trainer_id,
  client_user_id,
  rating,
  review,
  created_at,
  updated_at
`

type CreateReviewParams struct {
	BookingID    uuid.UUID
	TrainerID    uuid.UUID
	ClientUserID uuid.UUID
	Rating       int32
	Review       sql.NullString
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, createReview,
		arg.BookingID,
		arg.TrainerID,
		arg.ClientUserID,
		arg.Rating,
		arg.Review,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.TrainerID,
		&i.ClientUserID,
		&i.Rating,
		&i.Review,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainerReviews = `-- name: GetTrainerReviews :many
SELECT id, booking_id, trainer_id, client_user_id, rating, review, created_at, updated_at
FROM reviews
WHERE trainer_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetTrainerReviewsParams struct {
	TrainerID uuid.UUID
	Limit     int32
}

func (q *Queries) GetTrainerReviews(ctx context.Context, arg GetTrainerReviewsParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, getTrainerReviews, arg.TrainerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.TrainerID,
			&i.ClientUserID,
			&i.Rating,
			&i.Review,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainerReviewsAfterCursor = `-- name: ListTrainerReviewsAfterCursor :many
SELECT
  id,
  booking_id,
  trainer_id,
  client_user_id,
  rating,
  review,
  created_at,
  updated_at
FROM reviews
WHERE trainer_id = $1
  AND (created_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListTrainerReviewsAfterCursorParams struct {
	TrainerID       uuid.UUID
	CursorCreatedAt time.Time
	CursorID        uuid.UUID
	LimitCount      int32
}

func (q *Queries) ListTrainerReviewsAfterCursor(ctx context.Context, arg ListTrainerReviewsAfterCursorParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listTrainerReviewsAfterCursor,
		arg.TrainerID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.TrainerID,
			&i.ClientUserID,
			&i.Rating,
			&i.Review,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainerReviewsFirstPage = `-- name: ListTrainerReviewsFirstPage :many
SELECT
  id,
  booking_id,
  trainer_id,
  client_user_id,
  rating,
  review,
  created_at,
  updated_at
FROM reviews
WHERE trainer_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListTrainerReviewsFirstPageParams struct {
	TrainerID  uuid.UUID
	LimitCount int32
}

func (q *Queries) ListTrainerReviewsFirstPage(ctx context.Context, arg ListTrainerReviewsFirstPageParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listTrainerReviewsFirstPage, arg.TrainerID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.TrainerID,
			&i.ClientUserID,
			&i.Rating,
			&i.Review,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTrainerReviewStats = `-- name: RefreshTrainerReviewStats :one
UPDATE trainers
SET
  average_rating = (
    SELECT AVG(rating)::numeric
    FROM reviews AS r
    WHERE r.trainer_id = $1
  ),
  total_reviews = (
    SELECT COUNT(*)::int
    FROM reviews AS r
    WHERE r.trainer_id = $1
  ),
  updated_at = NOW()
WHERE id = $1
RETURNING
  id,
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,
  calendly_link,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
`

func (q *Queries) RefreshTrainerReviewStats(ctx context.Context, trainerID uuid.UUID) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, refreshTrainerReviewStats, trainerID)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.CalendlyConnected,
		&i.CalendlyLink,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
