// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignUserRoleParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, assignUserRole, arg.UserID, arg.RoleID)
	return err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, created_at FROM roles WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.created_at
FROM roles r
INNER JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userHasRole = `-- name: UserHasRole :one
SELECT EXISTS (
    SELECT 1 FROM user_roles ur
    INNER JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = $1 AND r.name = $2
) AS has_role
`

type UserHasRoleParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) UserHasRole(ctx context.Context, arg UserHasRoleParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasRole, arg.UserID, arg.Name)
	var has_role bool
	err := row.Scan(&has_role)
	return has_role, err
}
