// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const activateSubscription = `-- name: ActivateSubscription :one
UPDATE subscriptions
SET status = 'active'
WHERE id = $1
RETURNING
  id,
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  cancelled_at_period_end,
  created_at,
  cancelled_at
`

func (q *Queries) ActivateSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, activateSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelledAtPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const cancelSubscription = `-- name: CancelSubscription :one
UPDATE subscriptions
SET cancelled_at_period_end = true
WHERE id = $1
RETURNING
  id,
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  cancelled_at_period_end,
  created_at,
  cancelled_at
`

func (q *Queries) CancelSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, cancelSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelledAtPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const countSubscriptionUsage = `-- name: CountSubscriptionUsage :one
SELECT COUNT(*)
FROM subscription_usage
WHERE subscription_id = $1
`

func (q *Queries) CountSubscriptionUsage(ctx context.Context, subscriptionID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptionUsage, subscriptionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  cancelled_at_period_end
) VALUES (
  $1,
  $2,
  $3,
  $4,
  0,
  $5,
  $6,
  $7,
  $8,
  $9,
  false
)
RETURNING
  id,
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  cancelled_at_period_end,
  created_at,
  cancelled_at
`

type CreateSubscriptionParams struct {
	ClientID           uuid.UUID
	TrainerID          uuid.UUID
	PlanType           string
	SessionsPerMonth   int32
	Amount             int64
	Currency           string
	Status             string
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.ClientID,
		arg.TrainerID,
		arg.PlanType,
		arg.SessionsPerMonth,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelledAtPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT
  id,
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  cancelled_at_period_end,
  created_at,
  cancelled_at
FROM subscriptions
WHERE client_id = $1
  AND trainer_id = $2
  AND status = 'active'
LIMIT 1
`

type GetActiveSubscriptionParams struct {
	ClientID  uuid.UUID
	TrainerID uuid.UUID
}

func (q *Queries) GetActiveSubscription(ctx context.Context, arg GetActiveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscription, arg.ClientID, arg.TrainerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelledAtPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT
  id,
  subscription_id,
  booking_id,
  payer_id,
  provider,
  provider_transaction_id,
  idempotency_key,
  currency,
  total_amount,
  trainer_earning,
  platform_fee,
  payment_type,
  payment_status,
  paid_at,
  created_at
FROM payments
WHERE idempotency_key = $1
LIMIT 1
`

type GetPaymentByIdempotencyKeyRow struct {
	ID                    uuid.UUID
	SubscriptionID        uuid.NullUUID
	BookingID             uuid.NullUUID
	PayerID               uuid.UUID
	Provider              string
	ProviderTransactionID sql.NullString
	IdempotencyKey        string
	Currency              string
	TotalAmount           int64
	TrainerEarning        int64
	PlatformFee           int64
	PaymentType           string
	PaymentStatus         string
	PaidAt                sql.NullTime
	CreatedAt             time.Time
}

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetPaymentByIdempotencyKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i GetPaymentByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.BookingID,
		&i.PayerID,
		&i.Provider,
		&i.ProviderTransactionID,
		&i.IdempotencyKey,
		&i.Currency,
		&i.TotalAmount,
		&i.TrainerEarning,
		&i.PlatformFee,
		&i.PaymentType,
		&i.PaymentStatus,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByType = `-- name: GetPlanByType :one
SELECT
  id,
  plan_type,
  display_name,
  sessions_total,
  amount,
  currency,
  is_active,
  created_at,
  updated_at
FROM subscription_plans
WHERE plan_type = $1
  AND is_active = true
LIMIT 1
`

func (q *Queries) GetPlanByType(ctx context.Context, planType string) (SubscriptionPlan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByType, planType)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.PlanType,
		&i.DisplayName,
		&i.SessionsTotal,
		&i.Amount,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT
  id,
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  cancelled_at_period_end,
  created_at,
  cancelled_at
FROM subscriptions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelledAtPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT
  id,
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  cancelled_at_period_end,
  created_at,
  cancelled_at
FROM subscriptions
WHERE client_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListSubscriptionsParams struct {
	ClientID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptions, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.TrainerID,
			&i.PlanType,
			&i.SessionsPerMonth,
			&i.SessionsUsedThisMonth,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelledAtPeriodEnd,
			&i.CreatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
