// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const cancelSubscription = `-- name: CancelSubscription :one
UPDATE subscriptions
SET status = 'cancelled',
    cancelled_at = NOW()
WHERE id = $1
  AND status = 'active'
RETURNING id, client_id, trainer_id, plan_type, sessions_per_month, sessions_used_this_month, amount, currency, status, current_period_start, current_period_end, created_at, cancelled_at, plan_id, platform, trial_ends_at, apple_original_transaction_id, google_purchase_token
`

func (q *Queries) CancelSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, cancelSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.PlanID,
		&i.Platform,
		&i.TrialEndsAt,
		&i.AppleOriginalTransactionID,
		&i.GooglePurchaseToken,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    client_id,
    trainer_id,
    plan_id,
    plan_type,
    platform,
    sessions_per_month,
    amount,
    currency,
    status,
    trial_ends_at,
    current_period_start,
    current_period_end,
    apple_original_transaction_id,
    google_purchase_token
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    'USD',
    'active',
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, client_id, trainer_id, plan_type, sessions_per_month, sessions_used_this_month, amount, currency, status, current_period_start, current_period_end, created_at, cancelled_at, plan_id, platform, trial_ends_at, apple_original_transaction_id, google_purchase_token
`

type CreateSubscriptionParams struct {
	ClientID                   uuid.UUID
	TrainerID                  uuid.UUID
	PlanID                     sql.NullString
	PlanType                   string
	Platform                   sql.NullString
	SessionsPerMonth           sql.NullInt32
	Amount                     sql.NullInt64
	TrialEndsAt                sql.NullTime
	CurrentPeriodStart         sql.NullTime
	CurrentPeriodEnd           sql.NullTime
	AppleOriginalTransactionID sql.NullString
	GooglePurchaseToken        sql.NullString
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.ClientID,
		arg.TrainerID,
		arg.PlanID,
		arg.PlanType,
		arg.Platform,
		arg.SessionsPerMonth,
		arg.Amount,
		arg.TrialEndsAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.AppleOriginalTransactionID,
		arg.GooglePurchaseToken,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.PlanID,
		&i.Platform,
		&i.TrialEndsAt,
		&i.AppleOriginalTransactionID,
		&i.GooglePurchaseToken,
	)
	return i, err
}

const getActiveSubscriptionByClientID = `-- name: GetActiveSubscriptionByClientID :one
SELECT id, client_id, trainer_id, plan_type, sessions_per_month, sessions_used_this_month, amount, currency, status, current_period_start, current_period_end, created_at, cancelled_at, plan_id, platform, trial_ends_at, apple_original_transaction_id, google_purchase_token FROM subscriptions
WHERE client_id = $1
  AND status = 'active'
  AND current_period_end > NOW()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionByClientID(ctx context.Context, clientID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscriptionByClientID, clientID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.PlanID,
		&i.Platform,
		&i.TrialEndsAt,
		&i.AppleOriginalTransactionID,
		&i.GooglePurchaseToken,
	)
	return i, err
}

const getActiveSubscriptionForClient = `-- name: GetActiveSubscriptionForClient :one
SELECT id, client_id, trainer_id, plan_type, sessions_per_month, sessions_used_this_month, amount, currency, status, current_period_start, current_period_end, created_at, cancelled_at, plan_id, platform, trial_ends_at, apple_original_transaction_id, google_purchase_token FROM subscriptions
WHERE client_id = $1
  AND trainer_id = $2
  AND status = 'active'
  AND current_period_end > NOW()
LIMIT 1
`

type GetActiveSubscriptionForClientParams struct {
	ClientID  uuid.UUID
	TrainerID uuid.UUID
}

func (q *Queries) GetActiveSubscriptionForClient(ctx context.Context, arg GetActiveSubscriptionForClientParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscriptionForClient, arg.ClientID, arg.TrainerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.PlanID,
		&i.Platform,
		&i.TrialEndsAt,
		&i.AppleOriginalTransactionID,
		&i.GooglePurchaseToken,
	)
	return i, err
}

const getSubscriptionByAppleTransactionID = `-- name: GetSubscriptionByAppleTransactionID :one
SELECT id, client_id, trainer_id, plan_type, sessions_per_month, sessions_used_this_month, amount, currency, status, current_period_start, current_period_end, created_at, cancelled_at, plan_id, platform, trial_ends_at, apple_original_transaction_id, google_purchase_token FROM subscriptions
WHERE apple_original_transaction_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByAppleTransactionID(ctx context.Context, appleOriginalTransactionID sql.NullString) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByAppleTransactionID, appleOriginalTransactionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.PlanID,
		&i.Platform,
		&i.TrialEndsAt,
		&i.AppleOriginalTransactionID,
		&i.GooglePurchaseToken,
	)
	return i, err
}

const getSubscriptionByGooglePurchaseToken = `-- name: GetSubscriptionByGooglePurchaseToken :one
SELECT id, client_id, trainer_id, plan_type, sessions_per_month, sessions_used_this_month, amount, currency, status, current_period_start, current_period_end, created_at, cancelled_at, plan_id, platform, trial_ends_at, apple_original_transaction_id, google_purchase_token FROM subscriptions
WHERE google_purchase_token = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByGooglePurchaseToken(ctx context.Context, googlePurchaseToken sql.NullString) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByGooglePurchaseToken, googlePurchaseToken)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.PlanID,
		&i.Platform,
		&i.TrialEndsAt,
		&i.AppleOriginalTransactionID,
		&i.GooglePurchaseToken,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, client_id, trainer_id, plan_type, sessions_per_month, sessions_used_this_month, amount, currency, status, current_period_start, current_period_end, created_at, cancelled_at, plan_id, platform, trial_ends_at, apple_original_transaction_id, google_purchase_token FROM subscriptions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.PlanID,
		&i.Platform,
		&i.TrialEndsAt,
		&i.AppleOriginalTransactionID,
		&i.GooglePurchaseToken,
	)
	return i, err
}

const refundSessionCredit = `-- name: RefundSessionCredit :one
UPDATE subscriptions
SET sessions_used_this_month = GREATEST(0, sessions_used_this_month - 1)
WHERE id = $1
RETURNING id, client_id, trainer_id, plan_type, sessions_per_month, sessions_used_this_month, amount, currency, status, current_period_start, current_period_end, created_at, cancelled_at, plan_id, platform, trial_ends_at, apple_original_transaction_id, google_purchase_token
`

func (q *Queries) RefundSessionCredit(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, refundSessionCredit, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
		&i.PlanID,
		&i.Platform,
		&i.TrialEndsAt,
		&i.AppleOriginalTransactionID,
		&i.GooglePurchaseToken,
	)
	return i, err
}
