// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getActiveSubscriptionForClient = `-- name: GetActiveSubscriptionForClient :one
SELECT
  id,
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  created_at,
  cancelled_at
FROM subscriptions
WHERE client_id = $1
  AND trainer_id = $2
  AND status = 'active'
  AND current_period_end > NOW()
LIMIT 1
`

type GetActiveSubscriptionForClientParams struct {
	ClientID  uuid.UUID
	TrainerID uuid.UUID
}

func (q *Queries) GetActiveSubscriptionForClient(ctx context.Context, arg GetActiveSubscriptionForClientParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscriptionForClient, arg.ClientID, arg.TrainerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT
  id,
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  created_at,
  cancelled_at
FROM subscriptions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const refundSessionCredit = `-- name: RefundSessionCredit :one
UPDATE subscriptions
SET sessions_used_this_month = GREATEST(0, sessions_used_this_month - 1)
WHERE id = $1
RETURNING
  id,
  client_id,
  trainer_id,
  plan_type,
  sessions_per_month,
  sessions_used_this_month,
  amount,
  currency,
  status,
  current_period_start,
  current_period_end,
  created_at,
  cancelled_at
`

func (q *Queries) RefundSessionCredit(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, refundSessionCredit, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.TrainerID,
		&i.PlanType,
		&i.SessionsPerMonth,
		&i.SessionsUsedThisMonth,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.CancelledAt,
	)
	return i, err
}
