// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainer_benefits.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTrainerBenefit = `-- name: AddTrainerBenefit :one
INSERT INTO trainer_benefits (trainer_id, position, title, subtext)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, trainer_id, position, title, subtext, created_at
`

type AddTrainerBenefitParams struct {
	TrainerID uuid.UUID
	Position  int32
	Title     string
	Subtext   string
}

// Inserts one benefit at the supplied position. Used inside the
// POST /trainers transaction so the handler computes positions 1..N
// explicitly before sending the batch — that keeps the handler-side
// ordering deterministic without needing a MAX(position)+1 round-trip
// per row. The (trainer_id, position) unique index catches any handler
// bug that would double up.
func (q *Queries) AddTrainerBenefit(ctx context.Context, arg AddTrainerBenefitParams) (TrainerBenefit, error) {
	row := q.db.QueryRowContext(ctx, addTrainerBenefit,
		arg.TrainerID,
		arg.Position,
		arg.Title,
		arg.Subtext,
	)
	var i TrainerBenefit
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.Position,
		&i.Title,
		&i.Subtext,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllTrainerBenefits = `-- name: DeleteAllTrainerBenefits :exec
DELETE FROM trainer_benefits WHERE trainer_id = $1
`

// Used by the PATCH-style "replace all benefits" flow if/when we add one.
// Kept here so the wipe-and-rewrite pattern doesn't require a manual
// per-row delete loop.
func (q *Queries) DeleteAllTrainerBenefits(ctx context.Context, trainerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllTrainerBenefits, trainerID)
	return err
}

const deleteTrainerBenefit = `-- name: DeleteTrainerBenefit :execrows
DELETE FROM trainer_benefits
WHERE id = $1 AND trainer_id = $2
`

type DeleteTrainerBenefitParams struct {
	ID        uuid.UUID
	TrainerID uuid.UUID
}

// Deletes by benefit ID, but also requires the trainer_id to match so a
// typo can't delete another trainer's benefit. Returns rowcount so the
// handler can distinguish "deleted cleanly" from "wrong ID".
func (q *Queries) DeleteTrainerBenefit(ctx context.Context, arg DeleteTrainerBenefitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrainerBenefit, arg.ID, arg.TrainerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTrainerBenefits = `-- name: ListTrainerBenefits :many
SELECT id, trainer_id, position, title, subtext, created_at
FROM trainer_benefits
WHERE trainer_id = $1
ORDER BY position ASC
`

func (q *Queries) ListTrainerBenefits(ctx context.Context, trainerID uuid.UUID) ([]TrainerBenefit, error) {
	rows, err := q.db.QueryContext(ctx, listTrainerBenefits, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainerBenefit
	for rows.Next() {
		var i TrainerBenefit
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.Position,
			&i.Title,
			&i.Subtext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
