// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainers.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const approveTrainer = `-- name: ApproveTrainer :one
UPDATE trainers
SET
  onboarding_status = 'approved',
  updated_at        = NOW()
WHERE id = $1
RETURNING
  id,
  user_id,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at,
  specializations,
  training_styles
`

func (q *Queries) ApproveTrainer(ctx context.Context, id uuid.UUID) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, approveTrainer, id)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Specializations),
		pq.Array(&i.TrainingStyles),
	)
	return i, err
}

const countTrainers = `-- name: CountTrainers :one
SELECT COUNT(*) FROM trainers WHERE onboarding_status = 'approved'
`

func (q *Queries) CountTrainers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrainers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrainer = `-- name: CreateTrainer :one
INSERT INTO trainers (
  user_id,
  specializations,
  training_styles,
  bio,
  years_of_experience,
  display_picture,
  onboarding_status
) VALUES (
  $1,
  $2::text[],
  $3::text[],
  $4,
  $5,
  $6,
  COALESCE($7::text, 'pending')
)
RETURNING
  id,
  user_id,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at,
  specializations,
  training_styles
`

type CreateTrainerParams struct {
	UserID            uuid.UUID
	Specializations   []string
	TrainingStyles    []string
	Bio               sql.NullString
	YearsOfExperience sql.NullInt32
	DisplayPicture    sql.NullString
	OnboardingStatus  string
}

// Admin-only create. Inserts the trainer row whose user_id was just provisioned
// by UpsertTrainerUser (see users.sql). bio, intro_video_url stay NULL at
// create time — trainers fill those in themselves once they log in with the
// credentials emailed to them.
//
// Field order matches the physical column order of the trainers table (see
// migrations 005, 037, 038, 040) so sqlc reuses the db.Trainer struct rather
// than minting per-query Row structs; the alternative breaks every helper
// that already returns *db.Trainer.
func (q *Queries) CreateTrainer(ctx context.Context, arg CreateTrainerParams) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, createTrainer,
		arg.UserID,
		pq.Array(arg.Specializations),
		pq.Array(arg.TrainingStyles),
		arg.Bio,
		arg.YearsOfExperience,
		arg.DisplayPicture,
		arg.OnboardingStatus,
	)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Specializations),
		pq.Array(&i.TrainingStyles),
	)
	return i, err
}

const deleteTrainer = `-- name: DeleteTrainer :one
DELETE FROM trainers
WHERE id = $1
RETURNING
  id,
  user_id,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at,
  specializations,
  training_styles
`

func (q *Queries) DeleteTrainer(ctx context.Context, id uuid.UUID) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, deleteTrainer, id)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Specializations),
		pq.Array(&i.TrainingStyles),
	)
	return i, err
}

const getTrainerByID = `-- name: GetTrainerByID :one
SELECT
  id,
  user_id,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at,
  specializations,
  training_styles
FROM trainers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTrainerByID(ctx context.Context, id uuid.UUID) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, getTrainerByID, id)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Specializations),
		pq.Array(&i.TrainingStyles),
	)
	return i, err
}

const getTrainerByUserID = `-- name: GetTrainerByUserID :one
SELECT
  id,
  user_id,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at,
  specializations,
  training_styles
FROM trainers
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetTrainerByUserID(ctx context.Context, userID uuid.UUID) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, getTrainerByUserID, userID)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Specializations),
		pq.Array(&i.TrainingStyles),
	)
	return i, err
}

const listTrainers = `-- name: ListTrainers :many
SELECT
  id,
  user_id,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at,
  specializations,
  training_styles
FROM trainers
WHERE ($1::text = '' OR specializations @> ARRAY[$1]::text[])
ORDER BY created_at DESC
`

// Filter by a single specialization. The empty-string sentinel means "no
// filter". Containment uses the GIN index on specializations.
func (q *Queries) ListTrainers(ctx context.Context, dollar_1 string) ([]Trainer, error) {
	rows, err := q.db.QueryContext(ctx, listTrainers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trainer
	for rows.Next() {
		var i Trainer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Bio,
			&i.YearsOfExperience,
			&i.IntroVideoUrl,
			&i.DisplayPicture,
			&i.OnboardingStatus,
			&i.AverageRating,
			&i.TotalReviews,
			&i.CreatedAt,
			&i.UpdatedAt,
			pq.Array(&i.Specializations),
			pq.Array(&i.TrainingStyles),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrainer = `-- name: UpdateTrainer :one
UPDATE trainers
SET
  specializations     = COALESCE($1::text[], specializations),
  training_styles     = COALESCE($2::text[], training_styles),
  bio                 = COALESCE($3, bio),
  years_of_experience = COALESCE($4, years_of_experience),
  intro_video_url     = COALESCE($5, intro_video_url),
  display_picture     = COALESCE($6, display_picture),
  onboarding_status   = COALESCE($7::text, onboarding_status),
  updated_at          = NOW()
WHERE id = $8
RETURNING
  id,
  user_id,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at,
  specializations,
  training_styles
`

type UpdateTrainerParams struct {
	Specializations   []string
	TrainingStyles    []string
	Bio               sql.NullString
	YearsOfExperience sql.NullInt32
	IntroVideoUrl     sql.NullString
	DisplayPicture    sql.NullString
	OnboardingStatus  sql.NullString
	ID                uuid.UUID
}

// Partial update. Pass NULL to leave a column unchanged. specializations and
// training_styles use COALESCE on the array argument — pass NULL to keep
// existing values, an empty array to clear them.
func (q *Queries) UpdateTrainer(ctx context.Context, arg UpdateTrainerParams) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, updateTrainer,
		pq.Array(arg.Specializations),
		pq.Array(arg.TrainingStyles),
		arg.Bio,
		arg.YearsOfExperience,
		arg.IntroVideoUrl,
		arg.DisplayPicture,
		arg.OnboardingStatus,
		arg.ID,
	)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
		pq.Array(&i.Specializations),
		pq.Array(&i.TrainingStyles),
	)
	return i, err
}

const updateTrainerDisplayPicture = `-- name: UpdateTrainerDisplayPicture :execrows
UPDATE trainers
SET display_picture = $1,
    updated_at      = NOW()
WHERE id = $2
`

type UpdateTrainerDisplayPictureParams struct {
	DisplayPicture sql.NullString
	ID             uuid.UUID
}

// Partial display-picture-only update written by the background picture
// worker on successful MinIO upload. Same separation rationale as
// UpdateTrainerIntroVideo — the worker can't clobber a concurrent profile
// edit, and the rowcount distinguishes "trainer deleted before worker
// finished" from "updated cleanly".
func (q *Queries) UpdateTrainerDisplayPicture(ctx context.Context, arg UpdateTrainerDisplayPictureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTrainerDisplayPicture, arg.DisplayPicture, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTrainerIntroVideo = `-- name: UpdateTrainerIntroVideo :execrows
UPDATE trainers
SET intro_video_url = $1,
    updated_at      = NOW()
WHERE id = $2
`

type UpdateTrainerIntroVideoParams struct {
	IntroVideoUrl sql.NullString
	ID            uuid.UUID
}

// Partial intro-video-only update written by the background video worker on
// successful transcode + upload. Kept separate from any future
// UpdateTrainer-everything query so the worker can't race a concurrent
// profile edit and clobber other fields. Returns row count so the worker
// can distinguish "updated cleanly" from "trainer was deleted between
// upload start and DB write" — the latter is recorded as a terminal
// failure rather than silently orphaning the object in MinIO.
func (q *Queries) UpdateTrainerIntroVideo(ctx context.Context, arg UpdateTrainerIntroVideoParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTrainerIntroVideo, arg.IntroVideoUrl, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
