// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainers.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const approveTrainer = `-- name: ApproveTrainer :one
UPDATE trainers
SET
  onboarding_status = 'approved',
  updated_at        = NOW()
WHERE id = $1
RETURNING
  id,
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,
  calendly_link,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
`

func (q *Queries) ApproveTrainer(ctx context.Context, id uuid.UUID) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, approveTrainer, id)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.CalendlyConnected,
		&i.CalendlyLink,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrainer = `-- name: CreateTrainer :one
INSERT INTO trainers (
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,
  calendly_link,
  onboarding_status
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  COALESCE($7::boolean, false),
  $8,
  COALESCE($9::text, 'pending')
)
RETURNING
  id,
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,
  calendly_link,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
`

type CreateTrainerParams struct {
	UserID            uuid.UUID
	Specialization    sql.NullString
	Bio               sql.NullString
	YearsOfExperience sql.NullInt32
	IntroVideoUrl     sql.NullString
	DisplayPicture    sql.NullString
	CalendlyConnected bool
	CalendlyLink      sql.NullString
	OnboardingStatus  string
}

func (q *Queries) CreateTrainer(ctx context.Context, arg CreateTrainerParams) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, createTrainer,
		arg.UserID,
		arg.Specialization,
		arg.Bio,
		arg.YearsOfExperience,
		arg.IntroVideoUrl,
		arg.DisplayPicture,
		arg.CalendlyConnected,
		arg.CalendlyLink,
		arg.OnboardingStatus,
	)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.CalendlyConnected,
		&i.CalendlyLink,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrainer = `-- name: DeleteTrainer :one
DELETE FROM trainers
WHERE id = $1
RETURNING
  id,
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,
  calendly_link,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
`

func (q *Queries) DeleteTrainer(ctx context.Context, id uuid.UUID) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, deleteTrainer, id)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.CalendlyConnected,
		&i.CalendlyLink,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainerByID = `-- name: GetTrainerByID :one
SELECT
  id,
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,
  calendly_link,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
FROM trainers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTrainerByID(ctx context.Context, id uuid.UUID) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, getTrainerByID, id)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.CalendlyConnected,
		&i.CalendlyLink,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTrainers = `-- name: GetTrainers :many
SELECT
  id,
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,         
  calendly_link,
  onboarding_status,
  average_rating, 
  total_reviews,
  created_at,
  updated_at
FROM trainers
ORDER BY created_at DESC
`

func (q *Queries) GetTrainers(ctx context.Context) ([]Trainer, error) {
	rows, err := q.db.QueryContext(ctx, getTrainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trainer
	for rows.Next() {
		var i Trainer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Specialization,
			&i.Bio,
			&i.YearsOfExperience,
			&i.IntroVideoUrl,
			&i.DisplayPicture,
			&i.CalendlyConnected,
			&i.CalendlyLink,
			&i.OnboardingStatus,
			&i.AverageRating,
			&i.TotalReviews,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTrainers = `-- name: ListPendingTrainers :many
SELECT id, user_id, specialization, bio, years_of_experience, intro_video_url, display_picture, calendly_connected, calendly_link, onboarding_status, average_rating, total_reviews, created_at, updated_at 
FROM trainers 
WHERE onboarding_status = 'pending' 
ORDER BY created_at DESC
`

func (q *Queries) ListPendingTrainers(ctx context.Context) ([]Trainer, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTrainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trainer
	for rows.Next() {
		var i Trainer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Specialization,
			&i.Bio,
			&i.YearsOfExperience,
			&i.IntroVideoUrl,
			&i.DisplayPicture,
			&i.CalendlyConnected,
			&i.CalendlyLink,
			&i.OnboardingStatus,
			&i.AverageRating,
			&i.TotalReviews,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainerByUserID = `-- name: GetTrainerByUserID :one
SELECT
  id,
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,
  calendly_link,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
FROM trainers
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetTrainerByUserID(ctx context.Context, userID uuid.UUID) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, getTrainerByUserID, userID)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.CalendlyConnected,
		&i.CalendlyLink,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrainers = `-- name: ListTrainers :many
SELECT
  id,
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,
  calendly_link,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
FROM trainers
WHERE
  (
    $2::text IS NULL
    OR specialization = $2
  )
  AND (
    $3::int IS NULL
    OR years_of_experience >= $3
  )
  AND (
    $4::double precision IS NULL
    OR average_rating >= $4
  )
  AND onboarding_status = 'approved'
  
  AND (
    $5::timestamptz IS NULL
    OR created_at < $5
    OR (
      created_at = $5
      AND id < $6::uuid
    )
  )
ORDER BY created_at DESC, id DESC
LIMIT $1
`

type ListTrainersParams struct {
	Limit                int32
	Specialization       sql.NullString
	MinYearsOfExperience sql.NullInt32
	MinAverageRating     sql.NullFloat64
	CursorCreatedAt      sql.NullTime
	CursorID             uuid.NullUUID
}

func (q *Queries) ListTrainers(ctx context.Context, arg ListTrainersParams) ([]Trainer, error) {
	rows, err := q.db.QueryContext(ctx, listTrainers,
		arg.Limit,
		arg.Specialization,
		arg.MinYearsOfExperience,
		arg.MinAverageRating,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trainer
	for rows.Next() {
		var i Trainer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Specialization,
			&i.Bio,
			&i.YearsOfExperience,
			&i.IntroVideoUrl,
			&i.DisplayPicture,
			&i.CalendlyConnected,
			&i.CalendlyLink,
			&i.OnboardingStatus,
			&i.AverageRating,
			&i.TotalReviews,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrainer = `-- name: UpdateTrainer :one
UPDATE trainers
SET
  specialization      = COALESCE($1, specialization),
  bio                 = COALESCE($2, bio),
  years_of_experience = COALESCE($3, years_of_experience),
  intro_video_url     = COALESCE($4, intro_video_url),
  display_picture     = COALESCE($5, display_picture),
  calendly_connected  = COALESCE($6::boolean, calendly_connected),
  calendly_link       = COALESCE($7, calendly_link),
  onboarding_status   = COALESCE($8::text, onboarding_status),
  updated_at          = NOW()
WHERE id = $9
RETURNING
  id,
  user_id,
  specialization,
  bio,
  years_of_experience,
  intro_video_url,
  display_picture,
  calendly_connected,
  calendly_link,
  onboarding_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
`

type UpdateTrainerParams struct {
	Specialization    sql.NullString
	Bio               sql.NullString
	YearsOfExperience sql.NullInt32
	IntroVideoUrl     sql.NullString
	DisplayPicture    sql.NullString
	CalendlyConnected bool
	CalendlyLink      sql.NullString
	OnboardingStatus  string
	ID                uuid.UUID
}

func (q *Queries) UpdateTrainer(ctx context.Context, arg UpdateTrainerParams) (Trainer, error) {
	row := q.db.QueryRowContext(ctx, updateTrainer,
		arg.Specialization,
		arg.Bio,
		arg.YearsOfExperience,
		arg.IntroVideoUrl,
		arg.DisplayPicture,
		arg.CalendlyConnected,
		arg.CalendlyLink,
		arg.OnboardingStatus,
		arg.ID,
	)
	var i Trainer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Specialization,
		&i.Bio,
		&i.YearsOfExperience,
		&i.IntroVideoUrl,
		&i.DisplayPicture,
		&i.CalendlyConnected,
		&i.CalendlyLink,
		&i.OnboardingStatus,
		&i.AverageRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
