// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainer_availability.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTrainerAvailability = `-- name: CreateTrainerAvailability :one
INSERT INTO trainer_availability (trainer_id, day_of_week, start_time, end_time, timezone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, trainer_id, day_of_week, start_time, end_time, timezone, created_at, updated_at
`

type CreateTrainerAvailabilityParams struct {
	TrainerID uuid.UUID
	DayOfWeek int32
	StartTime time.Time
	EndTime   time.Time
	Timezone  string
}

func (q *Queries) CreateTrainerAvailability(ctx context.Context, arg CreateTrainerAvailabilityParams) (TrainerAvailability, error) {
	row := q.db.QueryRowContext(ctx, createTrainerAvailability,
		arg.TrainerID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.Timezone,
	)
	var i TrainerAvailability
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrainerAvailability = `-- name: DeleteTrainerAvailability :exec
DELETE FROM trainer_availability
WHERE trainer_id = $1
`

func (q *Queries) DeleteTrainerAvailability(ctx context.Context, trainerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTrainerAvailability, trainerID)
	return err
}

const listTrainerAvailability = `-- name: ListTrainerAvailability :many
SELECT id, trainer_id, day_of_week, start_time, end_time, timezone, created_at, updated_at
FROM trainer_availability
WHERE trainer_id = $1
ORDER BY day_of_week, start_time
`

func (q *Queries) ListTrainerAvailability(ctx context.Context, trainerID uuid.UUID) ([]TrainerAvailability, error) {
	rows, err := q.db.QueryContext(ctx, listTrainerAvailability, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainerAvailability
	for rows.Next() {
		var i TrainerAvailability
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
