// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainer_images.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addTrainerImage = `-- name: AddTrainerImage :one
WITH lock AS (
    SELECT pg_advisory_xact_lock(hashtext('trainer_image_position:' || $1::uuid::text))
),
next_pos AS (
    SELECT COALESCE(MAX(position) + 1, 1) AS pos
    FROM trainer_images
    WHERE trainer_id = $1::uuid
)
INSERT INTO trainer_images (trainer_id, image_url, position)
SELECT $1::uuid, $2, next_pos.pos
FROM next_pos, lock
RETURNING id, trainer_id, image_url, position, created_at
`

type AddTrainerImageParams struct {
	TrainerID uuid.UUID
	ImageUrl  string
}

// Inserts one image at the next free position for the trainer. The
// COALESCE(MAX(position)+1, 1) keeps the first image at position 1 instead
// of 0 — easier for clients (1-indexed is friendlier in URLs/UIs).
//
// Race-safety: pg_advisory_xact_lock(hashtext(...)) serialises concurrent
// inserts FOR THE SAME TRAINER (different trainers get different lock
// keys, so they don't contend). Without this, two workers reading MAX
// simultaneously would compute the same next position and the second
// INSERT would fail the (trainer_id, position) unique index — losing a
// gallery entry while leaving an orphaned object in MinIO. The lock is
// released automatically when the implicit statement transaction ends.
//
// Every use of @trainer_id is cast to ::uuid explicitly. sqlc otherwise
// infers the parameter's Go type from the *first* cast it sees, and the
// '::text' cast inside hashtext used to win — leaving the WHERE comparison
// as `uuid_column = text_param`, which Postgres rejects with
// ERRCODE 42883 "operator does not exist: uuid = text". The string concat
// in hashtext then double-casts ::uuid::text to keep the lock key stable.
func (q *Queries) AddTrainerImage(ctx context.Context, arg AddTrainerImageParams) (TrainerImage, error) {
	row := q.db.QueryRowContext(ctx, addTrainerImage, arg.TrainerID, arg.ImageUrl)
	var i TrainerImage
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.ImageUrl,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const countTrainerImages = `-- name: CountTrainerImages :one
SELECT COUNT(*) FROM trainer_images WHERE trainer_id = $1
`

func (q *Queries) CountTrainerImages(ctx context.Context, trainerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrainerImages, trainerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTrainerImage = `-- name: DeleteTrainerImage :execrows
DELETE FROM trainer_images
WHERE id = $1 AND trainer_id = $2
`

type DeleteTrainerImageParams struct {
	ID        uuid.UUID
	TrainerID uuid.UUID
}

// Deletes by image ID, but also requires the trainer_id match so an admin
// can't (via a typo in the URL) delete a different trainer's image. Returns
// row count so the handler can distinguish "deleted cleanly" from "wrong ID".
func (q *Queries) DeleteTrainerImage(ctx context.Context, arg DeleteTrainerImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTrainerImage, arg.ID, arg.TrainerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listTrainerImages = `-- name: ListTrainerImages :many
SELECT id, trainer_id, image_url, position, created_at
FROM trainer_images
WHERE trainer_id = $1
ORDER BY position ASC
`

func (q *Queries) ListTrainerImages(ctx context.Context, trainerID uuid.UUID) ([]TrainerImage, error) {
	rows, err := q.db.QueryContext(ctx, listTrainerImages, trainerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainerImage
	for rows.Next() {
		var i TrainerImage
		if err := rows.Scan(
			&i.ID,
			&i.TrainerID,
			&i.ImageUrl,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
