// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainer_invite_token.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTrainerInviteTokenByToken = `-- name: GetTrainerInviteTokenByToken :one
SELECT id, user_id, token, expires_at, used_at, created_at
FROM trainer_invite_tokens
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetTrainerInviteTokenByToken(ctx context.Context, token string) (TrainerInviteToken, error) {
	row := q.db.QueryRowContext(ctx, getTrainerInviteTokenByToken, token)
	var i TrainerInviteToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markTrainerInviteTokenUsed = `-- name: MarkTrainerInviteTokenUsed :exec
UPDATE trainer_invite_tokens
SET used_at = NOW()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkTrainerInviteTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markTrainerInviteTokenUsed, id)
	return err
}
