// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, auth_provider)
VALUES ($1, $2, $3)
ON CONFLICT (email, auth_provider) DO UPDATE
    SET updated_at = NOW()
RETURNING id, email, name, password, auth_provider, is_active, created_at, updated_at, role
`

type CreateUserParams struct {
	Email        string
	Name         string
	AuthProvider string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.AuthProvider)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password, auth_provider, is_active, created_at, updated_at, role
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByEmailAndProvider = `-- name: GetUserByEmailAndProvider :one
SELECT id, email, name, password, auth_provider, is_active, created_at, updated_at, role
FROM users
WHERE email = $1 AND auth_provider = $2
LIMIT 1
`

type GetUserByEmailAndProviderParams struct {
	Email        string
	AuthProvider string
}

func (q *Queries) GetUserByEmailAndProvider(ctx context.Context, arg GetUserByEmailAndProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailAndProvider, arg.Email, arg.AuthProvider)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password, auth_provider, is_active, created_at, updated_at, role
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getUserRoleByID = `-- name: GetUserRoleByID :one
SELECT role
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserRoleByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleByID, id)
	var role string
	err := row.Scan(&role)
	return role, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
   SET role       = $2,
       updated_at = NOW()
 WHERE id = $1
RETURNING id, email, name, password, auth_provider, is_active, created_at, updated_at, role
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const upsertAdminUser = `-- name: UpsertAdminUser :one
INSERT INTO users (email, name, password, auth_provider, role, is_active)
VALUES ($1, $2, $3, 'local', 'admin', true)
ON CONFLICT (email, auth_provider) DO UPDATE
   SET password   = EXCLUDED.password,
       name       = EXCLUDED.name,
       role       = 'admin',
       is_active  = true,
       updated_at = NOW()
RETURNING id, email, name, password, auth_provider, is_active, created_at, updated_at, role
`

type UpsertAdminUserParams struct {
	Email    string
	Name     string
	Password sql.NullString
}

func (q *Queries) UpsertAdminUser(ctx context.Context, arg UpsertAdminUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertAdminUser, arg.Email, arg.Name, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}
