// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_zoom_credentials.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteUserZoomCredentials = `-- name: DeleteUserZoomCredentials :execrows
DELETE FROM user_zoom_credentials WHERE user_id = $1
`

// DELETE /trainers/me/zoom. Returns rowcount so the handler can 404
// if the user never connected — clearer than returning 204 either way.
func (q *Queries) DeleteUserZoomCredentials(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserZoomCredentials, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUserZoomCredentials = `-- name: GetUserZoomCredentials :one
SELECT user_id, access_token_enc, refresh_token_enc, access_token_expires_at, scope, zoom_user_id, zoom_account_id, zoom_email, connected_at, last_success_at, last_failure_at, last_failure_reason FROM user_zoom_credentials WHERE user_id = $1
`

func (q *Queries) GetUserZoomCredentials(ctx context.Context, userID uuid.UUID) (UserZoomCredential, error) {
	row := q.db.QueryRowContext(ctx, getUserZoomCredentials, userID)
	var i UserZoomCredential
	err := row.Scan(
		&i.UserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scope,
		&i.ZoomUserID,
		&i.ZoomAccountID,
		&i.ZoomEmail,
		&i.ConnectedAt,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastFailureReason,
	)
	return i, err
}

const recordUserZoomFailure = `-- name: RecordUserZoomFailure :exec
UPDATE user_zoom_credentials
SET last_failure_at     = NOW(),
    last_failure_reason = LEFT($1::text, 500)
WHERE user_id = $2
`

type RecordUserZoomFailureParams struct {
	Reason string
	UserID uuid.UUID
}

// Surfaces the most recent failure on the user's connection so a
// "your Zoom connection appears broken" UI can render without us
// having to re-attempt the call just to find out. Kept short so the
// column doesn't grow unbounded.
func (q *Queries) RecordUserZoomFailure(ctx context.Context, arg RecordUserZoomFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordUserZoomFailure, arg.Reason, arg.UserID)
	return err
}

const recordUserZoomSuccess = `-- name: RecordUserZoomSuccess :exec
UPDATE user_zoom_credentials
SET last_success_at     = NOW(),
    last_failure_at     = NULL,
    last_failure_reason = NULL
WHERE user_id = $1
`

func (q *Queries) RecordUserZoomSuccess(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, recordUserZoomSuccess, userID)
	return err
}

const updateUserZoomTokens = `-- name: UpdateUserZoomTokens :one
UPDATE user_zoom_credentials
SET access_token_enc        = $1,
    refresh_token_enc       = $2,
    access_token_expires_at = $3,
    scope                   = $4,
    last_success_at         = NOW(),
    last_failure_at         = NULL,
    last_failure_reason     = NULL
WHERE user_id = $5
RETURNING user_id, access_token_enc, refresh_token_enc, access_token_expires_at, scope, zoom_user_id, zoom_account_id, zoom_email, connected_at, last_success_at, last_failure_at, last_failure_reason
`

type UpdateUserZoomTokensParams struct {
	AccessTokenEnc       string
	RefreshTokenEnc      string
	AccessTokenExpiresAt time.Time
	Scope                string
	UserID               uuid.UUID
}

// Called by the refresh path after a successful token rotation. Zoom
// returns a NEW refresh_token on every refresh (rolling refresh
// tokens) so both fields move together.
func (q *Queries) UpdateUserZoomTokens(ctx context.Context, arg UpdateUserZoomTokensParams) (UserZoomCredential, error) {
	row := q.db.QueryRowContext(ctx, updateUserZoomTokens,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.AccessTokenExpiresAt,
		arg.Scope,
		arg.UserID,
	)
	var i UserZoomCredential
	err := row.Scan(
		&i.UserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scope,
		&i.ZoomUserID,
		&i.ZoomAccountID,
		&i.ZoomEmail,
		&i.ConnectedAt,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastFailureReason,
	)
	return i, err
}

const upsertUserZoomCredentials = `-- name: UpsertUserZoomCredentials :one
INSERT INTO user_zoom_credentials (
    user_id,
    access_token_enc,
    refresh_token_enc,
    access_token_expires_at,
    scope,
    zoom_user_id,
    zoom_account_id,
    zoom_email
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    NULLIF($7::text, ''),
    NULLIF($8::text, '')
)
ON CONFLICT (user_id) DO UPDATE
   SET access_token_enc        = EXCLUDED.access_token_enc,
       refresh_token_enc       = EXCLUDED.refresh_token_enc,
       access_token_expires_at = EXCLUDED.access_token_expires_at,
       scope                   = EXCLUDED.scope,
       zoom_user_id            = EXCLUDED.zoom_user_id,
       zoom_account_id         = EXCLUDED.zoom_account_id,
       zoom_email              = EXCLUDED.zoom_email,
       connected_at            = NOW(),
       last_failure_at         = NULL,
       last_failure_reason     = NULL
RETURNING user_id, access_token_enc, refresh_token_enc, access_token_expires_at, scope, zoom_user_id, zoom_account_id, zoom_email, connected_at, last_success_at, last_failure_at, last_failure_reason
`

type UpsertUserZoomCredentialsParams struct {
	UserID               uuid.UUID
	AccessTokenEnc       string
	RefreshTokenEnc      string
	AccessTokenExpiresAt time.Time
	Scope                string
	ZoomUserID           string
	ZoomAccountID        string
	ZoomEmail            string
}

// Used by the OAuth callback handler after a successful token
// exchange. Single-row-per-user: reconnecting overwrites the previous
// credentials in place so we never accumulate stale grants for the
// same user. last_failure_* is cleared on every connect — a fresh
// grant should reset the failure surface.
func (q *Queries) UpsertUserZoomCredentials(ctx context.Context, arg UpsertUserZoomCredentialsParams) (UserZoomCredential, error) {
	row := q.db.QueryRowContext(ctx, upsertUserZoomCredentials,
		arg.UserID,
		arg.AccessTokenEnc,
		arg.RefreshTokenEnc,
		arg.AccessTokenExpiresAt,
		arg.Scope,
		arg.ZoomUserID,
		arg.ZoomAccountID,
		arg.ZoomEmail,
	)
	var i UserZoomCredential
	err := row.Scan(
		&i.UserID,
		&i.AccessTokenEnc,
		&i.RefreshTokenEnc,
		&i.AccessTokenExpiresAt,
		&i.Scope,
		&i.ZoomUserID,
		&i.ZoomAccountID,
		&i.ZoomEmail,
		&i.ConnectedAt,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.LastFailureReason,
	)
	return i, err
}
