// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_device.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserDevice = `-- name: CreateUserDevice :one
INSERT INTO user_device (user_id, device_token, platform) 
VALUES ($1, $2, $3)
ON CONFLICT (user_id, device_token)
DO UPDATE SET
    platform = EXCLUDED.platform,
    is_active = TRUE,
    is_push_notification_enabled = TRUE,
    updated_at = NOW()
RETURNING id, user_id, device_token, is_push_notification_enabled, platform, is_active, created_at, updated_at
`

type CreateUserDeviceParams struct {
	UserID      uuid.UUID
	DeviceToken string
	Platform    string
}

func (q *Queries) CreateUserDevice(ctx context.Context, arg CreateUserDeviceParams) (UserDevice, error) {
	row := q.db.QueryRowContext(ctx, createUserDevice, arg.UserID, arg.DeviceToken, arg.Platform)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceToken,
		&i.IsPushNotificationEnabled,
		&i.Platform,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUserDevice = `-- name: DeactivateUserDevice :exec
UPDATE user_device
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUserDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deactivateUserDevice, id)
	return err
}

const getAllActiveUsersDevices = `-- name: GetAllActiveUsersDevices :many
SELECT 
    id, 
    user_id,
    device_token,
    is_push_notification_enabled,
    platform,
    is_active,
    created_at,
    updated_at
FROM user_device
WHERE is_active = TRUE
`

func (q *Queries) GetAllActiveUsersDevices(ctx context.Context) ([]UserDevice, error) {
	rows, err := q.db.QueryContext(ctx, getAllActiveUsersDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceToken,
			&i.IsPushNotificationEnabled,
			&i.Platform,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceByToken = `-- name: GetDeviceByToken :one
SELECT 
    id, 
    user_id,
    device_token,
    is_push_notification_enabled,
    platform,
    is_active,
    created_at,
    updated_at
FROM user_device 
WHERE device_token = $1 
AND user_id = $2
LIMIT 1
`

type GetDeviceByTokenParams struct {
	DeviceToken string
	UserID      uuid.UUID
}

func (q *Queries) GetDeviceByToken(ctx context.Context, arg GetDeviceByTokenParams) (UserDevice, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByToken, arg.DeviceToken, arg.UserID)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceToken,
		&i.IsPushNotificationEnabled,
		&i.Platform,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDeviceByID = `-- name: GetUserDeviceByID :one
SELECT 
    id, 
    user_id,
    device_token,
    is_push_notification_enabled,
    platform,
    is_active,
    created_at,
    updated_at
FROM user_device 
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserDeviceByID(ctx context.Context, id uuid.UUID) (UserDevice, error) {
	row := q.db.QueryRowContext(ctx, getUserDeviceByID, id)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceToken,
		&i.IsPushNotificationEnabled,
		&i.Platform,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDevicesByUserID = `-- name: GetUserDevicesByUserID :many
SELECT 
    id, 
    user_id,
    device_token,
    is_push_notification_enabled,
    platform,
    is_active,
    created_at,
    updated_at
FROM user_device 
WHERE user_id = $1
`

func (q *Queries) GetUserDevicesByUserID(ctx context.Context, userID uuid.UUID) ([]UserDevice, error) {
	rows, err := q.db.QueryContext(ctx, getUserDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceToken,
			&i.IsPushNotificationEnabled,
			&i.Platform,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserActiveDevicesByUserID = `-- name: ListUserActiveDevicesByUserID :many
SELECT
    id, 
    user_id,
    device_token,
    is_push_notification_enabled,
    platform,
    is_active,
    created_at,
    updated_at
FROM user_device 
WHERE user_id = $1 
AND is_active = TRUE
`

func (q *Queries) ListUserActiveDevicesByUserID(ctx context.Context, userID uuid.UUID) ([]UserDevice, error) {
	rows, err := q.db.QueryContext(ctx, listUserActiveDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceToken,
			&i.IsPushNotificationEnabled,
			&i.Platform,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
