// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, auth_provider)
VALUES ($1, $2, $3)
ON CONFLICT (email, auth_provider) DO UPDATE
    SET updated_at = NOW()
RETURNING id, email, name, password, auth_provider, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	AuthProvider string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.AuthProvider)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailAndProvider = `-- name: GetUserByEmailAndProvider :one
SELECT id, email, name, password, auth_provider, is_active, created_at, updated_at FROM users WHERE email = $1 AND auth_provider = $2 LIMIT 1
`

type GetUserByEmailAndProviderParams struct {
	Email        string
	AuthProvider string
}

func (q *Queries) GetUserByEmailAndProvider(ctx context.Context, arg GetUserByEmailAndProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailAndProvider, arg.Email, arg.AuthProvider)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
