// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_codes.sql

package db

import (
	"context"
	"time"
)

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_codes (email, code, expires_at) VALUES ($1, $2, $3) RETURNING id, email, code, created_at, expires_at
`

type CreateVerificationCodeParams struct {
	Email     string
	Code      string
	ExpiresAt time.Time
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRowContext(ctx, createVerificationCode, arg.Email, arg.Code, arg.ExpiresAt)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteVerificationCodesByEmail = `-- name: DeleteVerificationCodesByEmail :exec
DELETE FROM verification_codes WHERE email = $1
`

func (q *Queries) DeleteVerificationCodesByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationCodesByEmail, email)
	return err
}

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT id, email, code, created_at, expires_at FROM verification_codes WHERE email = $1 AND code = $2 LIMIT 1
`

type GetVerificationCodeParams struct {
	Email string
	Code  string
}

func (q *Queries) GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRowContext(ctx, getVerificationCode, arg.Email, arg.Code)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
