// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waitlist.sql

package db

import (
	"context"
	"database/sql"
)

const addWaitlist = `-- name: AddWaitlist :execresult
INSERT INTO waitlist (email, feedback)
VALUES ($1, $2)
`

type AddWaitlistParams struct {
	Email    string
	Feedback string
}

func (q *Queries) AddWaitlist(ctx context.Context, arg AddWaitlistParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addWaitlist, arg.Email, arg.Feedback)
}

const getWaitlist = `-- name: GetWaitlist :many
SELECT id, email, feedback, created_at FROM waitlist
`

func (q *Queries) GetWaitlist(ctx context.Context) ([]Waitlist, error) {
	rows, err := q.db.QueryContext(ctx, getWaitlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Waitlist
	for rows.Next() {
		var i Waitlist
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Feedback,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
