// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: waitlist.sql

package db

import (
	"context"
	"database/sql"
)

const addWaitlist = `-- name: AddWaitlist :execresult
INSERT INTO waitlist (email, phone_number, location, name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) DO NOTHING
`

type AddWaitlistParams struct {
	Email       string
	PhoneNumber string
	Location    string
	Name        string
}

func (q *Queries) AddWaitlist(ctx context.Context, arg AddWaitlistParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addWaitlist,
		arg.Email,
		arg.PhoneNumber,
		arg.Location,
		arg.Name,
	)
}

const getSingleWaitlist = `-- name: GetSingleWaitlist :one
SELECT id, email, created_at, phone_number, location, name FROM waitlist
WHERE email = $1
`

func (q *Queries) GetSingleWaitlist(ctx context.Context, email string) (Waitlist, error) {
	row := q.db.QueryRowContext(ctx, getSingleWaitlist, email)
	var i Waitlist
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.PhoneNumber,
		&i.Location,
		&i.Name,
	)
	return i, err
}

const getWaitlist = `-- name: GetWaitlist :many
SELECT id, email, created_at, phone_number, location, name FROM waitlist
`

func (q *Queries) GetWaitlist(ctx context.Context) ([]Waitlist, error) {
	rows, err := q.db.QueryContext(ctx, getWaitlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Waitlist
	for rows.Next() {
		var i Waitlist
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.CreatedAt,
			&i.PhoneNumber,
			&i.Location,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
