// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO trainer_wallet_ledger (
  trainer_id,
  transaction_type,
  reference_type,
  reference_id,
  amount,
  balance_before,
  balance_after
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING
  id,
  trainer_id,
  transaction_type,
  reference_type,
  reference_id,
  amount,
  balance_before,
  balance_after,
  created_at
`

type CreateLedgerEntryParams struct {
	TrainerID       uuid.UUID
	TransactionType string
	ReferenceType   string
	ReferenceID     uuid.UUID
	Amount          int64
	BalanceBefore   int64
	BalanceAfter    int64
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (TrainerWalletLedger, error) {
	row := q.db.QueryRowContext(ctx, createLedgerEntry,
		arg.TrainerID,
		arg.TransactionType,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Amount,
		arg.BalanceBefore,
		arg.BalanceAfter,
	)
	var i TrainerWalletLedger
	err := row.Scan(
		&i.ID,
		&i.TrainerID,
		&i.TransactionType,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Amount,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTrainerWallet = `-- name: UpsertTrainerWallet :one
INSERT INTO trainer_wallets (trainer_id, current_balance, total_earned, total_paid_out)
VALUES ($1, $2, $2, 0)
ON CONFLICT (trainer_id) DO UPDATE
SET
  current_balance = trainer_wallets.current_balance + $2,
  total_earned    = trainer_wallets.total_earned + $2,
  updated_at      = NOW()
RETURNING
  trainer_id,
  current_balance,
  total_earned,
  total_paid_out,
  updated_at
`

type UpsertTrainerWalletParams struct {
	TrainerID uuid.UUID
	Amount    int64
}

func (q *Queries) UpsertTrainerWallet(ctx context.Context, arg UpsertTrainerWalletParams) (TrainerWallet, error) {
	row := q.db.QueryRowContext(ctx, upsertTrainerWallet, arg.TrainerID, arg.Amount)
	var i TrainerWallet
	err := row.Scan(
		&i.TrainerID,
		&i.CurrentBalance,
		&i.TotalEarned,
		&i.TotalPaidOut,
		&i.UpdatedAt,
	)
	return i, err
}
