-- +goose Up
ALTER TABLE waitlist
ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20) NOT NULL DEFAULT '0',
ADD COLUMN IF NOT EXISTS location VARCHAR(255) NOT NULL DEFAULT 'nil',
ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL DEFAULT 'nil';



-- +goose Down
ALTER TABLE waitlist
DROP COLUMN IF EXISTS phone_number,
DROP COLUMN IF EXISTS location,
DROP COLUMN IF EXISTS name;