// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for BaseResponseStatus.
const (
	BaseResponseStatusError   BaseResponseStatus = "error"
	BaseResponseStatusSuccess BaseResponseStatus = "success"
)

// Valid indicates whether the value is a known member of the BaseResponseStatus enum.
func (e BaseResponseStatus) Valid() bool {
	switch e {
	case BaseResponseStatusError:
		return true
	case BaseResponseStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseStatus.
const (
	ErrorResponseStatusError   ErrorResponseStatus = "error"
	ErrorResponseStatusSuccess ErrorResponseStatus = "success"
)

// Valid indicates whether the value is a known member of the ErrorResponseStatus enum.
func (e ErrorResponseStatus) Valid() bool {
	switch e {
	case ErrorResponseStatusError:
		return true
	case ErrorResponseStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for SuccessResponseStatus.
const (
	Error   SuccessResponseStatus = "error"
	Success SuccessResponseStatus = "success"
)

// Valid indicates whether the value is a known member of the SuccessResponseStatus enum.
func (e SuccessResponseStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Success:
		return true
	default:
		return false
	}
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Code Machine-readable response code (e.g., OK, BAD_REQUEST, NOT_FOUND)
	Code    string             `json:"code"`
	Message string             `json:"message"`
	Status  BaseResponseStatus `json:"status"`
}

// BaseResponseStatus defines model for BaseResponse.Status.
type BaseResponseStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable response code (e.g., OK, BAD_REQUEST, NOT_FOUND)
	Code    string              `json:"code"`
	Errors  *[]FieldError       `json:"errors,omitempty"`
	Message string              `json:"message"`
	Status  ErrorResponseStatus `json:"status"`
}

// ErrorResponseStatus defines model for ErrorResponse.Status.
type ErrorResponseStatus string

// FieldError defines model for FieldError.
type FieldError struct {
	// Field The field that failed validation
	Field string `json:"field"`

	// Message Human-readable error message for this field
	Message string `json:"message"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	// Code Machine-readable response code (e.g., OK, BAD_REQUEST, NOT_FOUND)
	Code string `json:"code"`

	// Data Response payload (omitted when null)
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`

	// Meta Pagination or additional metadata (omitted when null)
	Meta   *map[string]interface{} `json:"meta,omitempty"`
	Status SuccessResponseStatus   `json:"status"`
}

// SuccessResponseStatus defines model for SuccessResponse.Status.
type SuccessResponseStatus string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// HandleGoogleCallbackParams defines parameters for HandleGoogleCallback.
type HandleGoogleCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// HandleLocalAuthJSONBody defines parameters for HandleLocalAuth.
type HandleLocalAuthJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// HandleGetWaitlistParams defines parameters for HandleGetWaitlist.
type HandleGetWaitlistParams struct {
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}

// HandleAddWaitlistJSONBody defines parameters for HandleAddWaitlist.
type HandleAddWaitlistJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// HandleLocalAuthJSONRequestBody defines body for HandleLocalAuth for application/json ContentType.
type HandleLocalAuthJSONRequestBody HandleLocalAuthJSONBody

// HandleAddWaitlistJSONRequestBody defines body for HandleAddWaitlist for application/json ContentType.
type HandleAddWaitlistJSONRequestBody HandleAddWaitlistJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Root endpoint
	// (GET /)
	Root(c *gin.Context)
	// Initiate Google OAuth — redirects browser to Google consent screen
	// (GET /auth/google)
	HandleGoogleLogin(c *gin.Context)
	// Handle Google OAuth callback and return JWT tokens
	// (GET /auth/google/callback)
	HandleGoogleCallback(c *gin.Context, params HandleGoogleCallbackParams)
	// Login with email and password
	// (POST /auth/login)
	HandleLocalAuth(c *gin.Context)
	// Health check endpoint
	// (GET /health)
	HealthCheck(c *gin.Context)
	// Handle getting emails or filtered emails in waitlist
	// (GET /waitlist)
	HandleGetWaitlist(c *gin.Context, params HandleGetWaitlistParams)
	// Handle adding an email address to the waitlist table
	// (POST /waitlist)
	HandleAddWaitlist(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Root operation middleware
func (siw *ServerInterfaceWrapper) Root(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Root(c)
}

// HandleGoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) HandleGoogleLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HandleGoogleLogin(c)
}

// HandleGoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) HandleGoogleCallback(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleGoogleCallbackParams

	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", c.Request.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", c.Request.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HandleGoogleCallback(c, params)
}

// HandleLocalAuth operation middleware
func (siw *ServerInterfaceWrapper) HandleLocalAuth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HandleLocalAuth(c)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// HandleGetWaitlist operation middleware
func (siw *ServerInterfaceWrapper) HandleGetWaitlist(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleGetWaitlistParams

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "email", c.Request.URL.Query(), &params.Email, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter email: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HandleGetWaitlist(c, params)
}

// HandleAddWaitlist operation middleware
func (siw *ServerInterfaceWrapper) HandleAddWaitlist(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HandleAddWaitlist(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/", wrapper.Root)
	router.GET(options.BaseURL+"/auth/google", wrapper.HandleGoogleLogin)
	router.GET(options.BaseURL+"/auth/google/callback", wrapper.HandleGoogleCallback)
	router.POST(options.BaseURL+"/auth/login", wrapper.HandleLocalAuth)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck)
	router.GET(options.BaseURL+"/waitlist", wrapper.HandleGetWaitlist)
	router.POST(options.BaseURL+"/waitlist", wrapper.HandleAddWaitlist)
}
