// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

<<<<<<< HEAD
const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for BaseResponseStatus.
=======
>>>>>>> 7c0dede (Refactored Trainer Management logic based on PR comments)
const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AuthUserUserType.
const (
	Admin   AuthUserUserType = "admin"
	Client  AuthUserUserType = "client"
	Trainer AuthUserUserType = "trainer"
)

// Valid indicates whether the value is a known member of the AuthUserUserType enum.
func (e AuthUserUserType) Valid() bool {
	switch e {
	case Admin:
		return true
	case Client:
		return true
	case Trainer:
		return true
	default:
		return false
	}
}

// Defines values for CreateTrainerRequestOnboardingStatus.
const (
	CreateTrainerRequestOnboardingStatusApproved  CreateTrainerRequestOnboardingStatus = "approved"
	CreateTrainerRequestOnboardingStatusPending   CreateTrainerRequestOnboardingStatus = "pending"
	CreateTrainerRequestOnboardingStatusRejected  CreateTrainerRequestOnboardingStatus = "rejected"
	CreateTrainerRequestOnboardingStatusSuspended CreateTrainerRequestOnboardingStatus = "suspended"
)

// Valid indicates whether the value is a known member of the CreateTrainerRequestOnboardingStatus enum.
func (e CreateTrainerRequestOnboardingStatus) Valid() bool {
	switch e {
	case CreateTrainerRequestOnboardingStatusApproved:
		return true
	case CreateTrainerRequestOnboardingStatusPending:
		return true
	case CreateTrainerRequestOnboardingStatusRejected:
		return true
	case CreateTrainerRequestOnboardingStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseStatus.
const (
	ErrorResponseStatusError   ErrorResponseStatus = "error"
	ErrorResponseStatusSuccess ErrorResponseStatus = "success"
)

// Valid indicates whether the value is a known member of the ErrorResponseStatus enum.
func (e ErrorResponseStatus) Valid() bool {
	switch e {
	case ErrorResponseStatusError:
		return true
	case ErrorResponseStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for SuccessResponseStatus.
const (
	SuccessResponseStatusError   SuccessResponseStatus = "error"
	SuccessResponseStatusSuccess SuccessResponseStatus = "success"
)

// Valid indicates whether the value is a known member of the SuccessResponseStatus enum.
func (e SuccessResponseStatus) Valid() bool {
	switch e {
	case SuccessResponseStatusError:
		return true
	case SuccessResponseStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for UpdateTrainerRequestOnboardingStatus.
const (
	UpdateTrainerRequestOnboardingStatusApproved  UpdateTrainerRequestOnboardingStatus = "approved"
	UpdateTrainerRequestOnboardingStatusPending   UpdateTrainerRequestOnboardingStatus = "pending"
	UpdateTrainerRequestOnboardingStatusRejected  UpdateTrainerRequestOnboardingStatus = "rejected"
	UpdateTrainerRequestOnboardingStatusSuspended UpdateTrainerRequestOnboardingStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UpdateTrainerRequestOnboardingStatus enum.
func (e UpdateTrainerRequestOnboardingStatus) Valid() bool {
	switch e {
	case UpdateTrainerRequestOnboardingStatusApproved:
		return true
	case UpdateTrainerRequestOnboardingStatusPending:
		return true
	case UpdateTrainerRequestOnboardingStatusRejected:
		return true
	case UpdateTrainerRequestOnboardingStatusSuspended:
		return true
	default:
		return false
	}
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Email           string             `json:"email"`
	Id              openapi_types.UUID `json:"id"`
	Name            string             `json:"name"`
	ProfileComplete bool               `json:"profile_complete"`
	UserType        AuthUserUserType   `json:"user_type"`
}

// AuthUserUserType defines model for AuthUser.UserType.
type AuthUserUserType string

// CreateTrainerRequest defines model for CreateTrainerRequest.
type CreateTrainerRequest struct {
	Bio               *string                               `json:"bio,omitempty"`
	CalendlyConnected *bool                                 `json:"calendly_connected,omitempty"`
	CalendlyLink      *string                               `json:"calendly_link,omitempty"`
	DisplayPicture    *string                               `json:"display_picture,omitempty"`
	IntroVideoUrl     *string                               `json:"intro_video_url,omitempty"`
	OnboardingStatus  *CreateTrainerRequestOnboardingStatus `json:"onboarding_status,omitempty"`
	Specialization    *string                               `json:"specialization,omitempty"`
	UserId            openapi_types.UUID                    `json:"user_id"`
	YearsOfExperience *int                                  `json:"years_of_experience,omitempty"`
}

// CreateTrainerRequestOnboardingStatus defines model for CreateTrainerRequest.OnboardingStatus.
type CreateTrainerRequestOnboardingStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string              `json:"code"`
	Errors  *[]FieldError       `json:"errors,omitempty"`
	Message string              `json:"message"`
	Status  ErrorResponseStatus `json:"status"`
}

// ErrorResponseStatus defines model for ErrorResponse.Status.
type ErrorResponseStatus string

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// GoogleAuthResponse defines model for GoogleAuthResponse.
type GoogleAuthResponse struct {
	Data struct {
		AccessToken  string   `json:"access_token"`
		ExpiresIn    int      `json:"expires_in"`
		IsNewUser    bool     `json:"is_new_user"`
		RefreshToken string   `json:"refresh_token"`
		User         AuthUser `json:"user"`
	} `json:"data"`
	Message string `json:"message"`
	Status  string `json:"status"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Code    string                  `json:"code"`
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message string                  `json:"message"`
	Meta    *map[string]interface{} `json:"meta,omitempty"`
	Status  SuccessResponseStatus   `json:"status"`
}

// SuccessResponseStatus defines model for SuccessResponse.Status.
type SuccessResponseStatus string

<<<<<<< HEAD
// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string
=======
// UpdateTrainerRequest defines model for UpdateTrainerRequest.
type UpdateTrainerRequest struct {
	Bio               *string                               `json:"bio,omitempty"`
	CalendlyConnected *bool                                 `json:"calendly_connected,omitempty"`
	CalendlyLink      *string                               `json:"calendly_link,omitempty"`
	DisplayPicture    *string                               `json:"display_picture,omitempty"`
	IntroVideoUrl     *string                               `json:"intro_video_url,omitempty"`
	OnboardingStatus  *UpdateTrainerRequestOnboardingStatus `json:"onboarding_status,omitempty"`
	Specialization    *string                               `json:"specialization,omitempty"`
	YearsOfExperience *int                                  `json:"years_of_experience,omitempty"`
}

// UpdateTrainerRequestOnboardingStatus defines model for UpdateTrainerRequest.OnboardingStatus.
type UpdateTrainerRequestOnboardingStatus string
>>>>>>> 7c0dede (Refactored Trainer Management logic based on PR comments)

// HandleGoogleCallbackParams defines parameters for HandleGoogleCallback.
type HandleGoogleCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// GetTrainersParams defines parameters for GetTrainers.
type GetTrainersParams struct {
	// Category Filter by category (maps to trainers.specialization)
	Category *string `form:"category,omitempty" json:"category,omitempty"`
}

<<<<<<< HEAD
// HandleGetWaitlistParams defines parameters for HandleGetWaitlist.
type HandleGetWaitlistParams struct {
	Email *string `form:"email,omitempty" json:"email,omitempty"`
}

// HandleAddWaitlistJSONBody defines parameters for HandleAddWaitlist.
type HandleAddWaitlistJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// HandleLocalAuthJSONRequestBody defines body for HandleLocalAuth for application/json ContentType.
type HandleLocalAuthJSONRequestBody HandleLocalAuthJSONBody
=======
// CreateTrainerJSONRequestBody defines body for CreateTrainer for application/json ContentType.
type CreateTrainerJSONRequestBody = CreateTrainerRequest

// UpdateTrainerJSONRequestBody defines body for UpdateTrainer for application/json ContentType.
type UpdateTrainerJSONRequestBody = UpdateTrainerRequest
>>>>>>> 7c0dede (Refactored Trainer Management logic based on PR comments)

// HandleAddWaitlistJSONRequestBody defines body for HandleAddWaitlist for application/json ContentType.
type HandleAddWaitlistJSONRequestBody HandleAddWaitlistJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /)
	Root(c *gin.Context)
	// Initiate Google OAuth — redirects browser to Google consent screen
	// (GET /auth/google)
	HandleGoogleLogin(c *gin.Context)
	// Handle Google OAuth callback and return JWT tokens
	// (GET /auth/google/callback)
	HandleGoogleCallback(c *gin.Context, params HandleGoogleCallbackParams)

	// (POST /auth/login)
	HandleLocalAuth(c *gin.Context)

	// (GET /health)
	HealthCheck(c *gin.Context)
<<<<<<< HEAD
	// Handle getting emails or filtered emails in waitlist
	// (GET /waitlist)
	HandleGetWaitlist(c *gin.Context, params HandleGetWaitlistParams)
	// Handle adding an email address to the waitlist table
	// (POST /waitlist)
	HandleAddWaitlist(c *gin.Context)
=======
	// Get trainers (admin only)
	// (GET /trainers)
	GetTrainers(c *gin.Context, params GetTrainersParams)
	// Add trainer (admin only)
	// (POST /trainers)
	CreateTrainer(c *gin.Context)
	// Delete trainer (admin only)
	// (DELETE /trainers/{id})
	DeleteTrainer(c *gin.Context, id openapi_types.UUID)
	// Get trainer by ID (admin only)
	// (GET /trainers/{id})
	GetTrainerByID(c *gin.Context, id openapi_types.UUID)
	// Update trainer (admin only)
	// (PUT /trainers/{id})
	UpdateTrainer(c *gin.Context, id openapi_types.UUID)
>>>>>>> 7c0dede (Refactored Trainer Management logic based on PR comments)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Root operation middleware
func (siw *ServerInterfaceWrapper) Root(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Root(c)
}

// HandleGoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) HandleGoogleLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HandleGoogleLogin(c)
}

// HandleGoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) HandleGoogleCallback(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleGoogleCallbackParams

	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", c.Request.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter code: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", c.Request.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter state: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HandleGoogleCallback(c, params)
}

// HandleLocalAuth operation middleware
func (siw *ServerInterfaceWrapper) HandleLocalAuth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HandleLocalAuth(c)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

<<<<<<< HEAD
// HandleGetWaitlist operation middleware
func (siw *ServerInterfaceWrapper) HandleGetWaitlist(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleGetWaitlistParams

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "email", c.Request.URL.Query(), &params.Email, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter email: %w", err), http.StatusBadRequest)
=======
// GetTrainers operation middleware
func (siw *ServerInterfaceWrapper) GetTrainers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrainersParams

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", c.Request.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category: %w", err), http.StatusBadRequest)
>>>>>>> 7c0dede (Refactored Trainer Management logic based on PR comments)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

<<<<<<< HEAD
	siw.Handler.HandleGetWaitlist(c, params)
}

// HandleAddWaitlist operation middleware
func (siw *ServerInterfaceWrapper) HandleAddWaitlist(c *gin.Context) {
=======
	siw.Handler.GetTrainers(c, params)
}

// CreateTrainer operation middleware
func (siw *ServerInterfaceWrapper) CreateTrainer(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})
>>>>>>> 7c0dede (Refactored Trainer Management logic based on PR comments)

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

<<<<<<< HEAD
	siw.Handler.HandleAddWaitlist(c)
=======
	siw.Handler.CreateTrainer(c)
}

// DeleteTrainer operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrainer(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTrainer(c, id)
}

// GetTrainerByID operation middleware
func (siw *ServerInterfaceWrapper) GetTrainerByID(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTrainerByID(c, id)
}

// UpdateTrainer operation middleware
func (siw *ServerInterfaceWrapper) UpdateTrainer(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTrainer(c, id)
>>>>>>> 7c0dede (Refactored Trainer Management logic based on PR comments)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/", wrapper.Root)
	router.GET(options.BaseURL+"/auth/google", wrapper.HandleGoogleLogin)
	router.GET(options.BaseURL+"/auth/google/callback", wrapper.HandleGoogleCallback)
	router.POST(options.BaseURL+"/auth/login", wrapper.HandleLocalAuth)
	router.GET(options.BaseURL+"/health", wrapper.HealthCheck)
<<<<<<< HEAD
	router.GET(options.BaseURL+"/waitlist", wrapper.HandleGetWaitlist)
	router.POST(options.BaseURL+"/waitlist", wrapper.HandleAddWaitlist)
=======
	router.GET(options.BaseURL+"/trainers", wrapper.GetTrainers)
	router.POST(options.BaseURL+"/trainers", wrapper.CreateTrainer)
	router.DELETE(options.BaseURL+"/trainers/:id", wrapper.DeleteTrainer)
	router.GET(options.BaseURL+"/trainers/:id", wrapper.GetTrainerByID)
	router.PUT(options.BaseURL+"/trainers/:id", wrapper.UpdateTrainer)
>>>>>>> 7c0dede (Refactored Trainer Management logic based on PR comments)
}
