// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Session struct {
	ID        string
	UserID    string
	Token     string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID           string
	Email        string
	Name         string
	Password     sql.NullString
	AuthProvider string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type VerificationCode struct {
	ID        string
	Email     string
	Code      string
	CreatedAt time.Time
	ExpiresAt time.Time
}
