// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users
SET name = $1, is_active = true, updated_at = NOW()
WHERE id = $2
`

type ActivateUserParams struct {
	Name string
	ID   string
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) error {
	_, err := q.db.ExecContext(ctx, activateUser, arg.Name, arg.ID)
	return err
}

const createLocalUser = `-- name: CreateLocalUser :one
INSERT INTO users (email, name, auth_provider, is_active)
VALUES ($1, $2, 'local', false)
RETURNING id, email, name, password, auth_provider, is_active, created_at, updated_at
`

type CreateLocalUserParams struct {
	Email string
	Name  string
}

func (q *Queries) CreateLocalUser(ctx context.Context, arg CreateLocalUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createLocalUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, auth_provider)
VALUES ($1, $2, $3)
RETURNING id, email, name, password, auth_provider, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	AuthProvider string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.AuthProvider)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password, auth_provider, is_active, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailAndProvider = `-- name: GetUserByEmailAndProvider :one
SELECT id, email, name, password, auth_provider, is_active, created_at, updated_at
FROM users
WHERE
    email = $1
    AND auth_provider = $2
LIMIT 1
`

type GetUserByEmailAndProviderParams struct {
	Email        string
	AuthProvider string
}

func (q *Queries) GetUserByEmailAndProvider(ctx context.Context, arg GetUserByEmailAndProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailAndProvider, arg.Email, arg.AuthProvider)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Password,
		&i.AuthProvider,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	Password sql.NullString
	ID       string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}
